### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by FML128** [bkbilly/lnxlink#100]
### What type of installation are you running?

Desktop

### Which Linux OS are you using?

Arch Linux

### Which version of LNXLink has the issue?

2024.2.2

### The problem

It cannot start. Even with debug log I cannot see why. The log is attached below.

### Logs

[gaming@gamingtv ~]$ lnxlink -c lnxlink.yaml -l DEBUG
INFO:lnxlink:LNXlink 2024.2.2, Python 3.11.8
INFO:lnxlink:Loaded addons: required_restart, update, shutdown, idle, bash, suspend, restart, camera_used, wifi, disk_usage, systemd, notify, network, microphone_used, gpu, cpu, keep_alive, display_env, audio_select, temperature, sys_updates, xdg_open, memory, screen_onoff
INFO:lnxlink:No systemd settings found on configuration.
INFO:lnxlink:MQTT connection: Success
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.github.com:443
DEBUG:urllib3.connectionpool:https://api.github.com:443 "GET /repos/bkbilly/lnxlink/releases/latest HTTP/1.1" 200 892
Segmentation fault (core dumped)

**Comment by bkbilly** [comment]
I think I've encountered this issue before and it had to do with the **idle** module.
You could try installing **xprintidle** package or try adding the **idle** to the exclude modules list on your **lnxlink.yaml** config.

**Comment by bkbilly** [comment]
I found the issue on the idle module.
It's using the `dbus_idle` package which I've updated it, so I would recommend updating this to version `2024.3.0`.

This should be done automatically on the next release of LNXlink.

**Comment by FML128** [comment]
Thank you, it was the idle module. However, upgrading version to 2024.3.0 and installing xprintidle did not fix the issue.

**Comment by FML128** [comment]
This is still not fixed in 2024.3.0

**Comment by bkbilly** [comment]
You should try the new version of LNXlink 2024.4.0.

**Comment by bkbilly** [comment]
This seems to be inactive so I am closing it.
The fix was introduced with the new version of dbus_idle.
