### ISSUE TITLE
Running via systemd does not work

### ISSUE THREAD

**Issue by FuzzyMistborn** [bkbilly/lnxlink#103]
### What type of installation are you running?

Desktop

### Which Linux OS are you using?

Fedora 40

### Which version of LNXLink has the issue?

2024.05

### Describe the problem

I tried installing on Fedora 40.  Everything works when I run the command in the terminal, but when I tried to run via systemd it kept failing/not running, showing a service 203/Exec error.

### Additional context

Based on my searching for a solution, it seems SELinux doesn't like things outside "normal" paths.  So `/home/USER/.local/bin/lnxlink` doesn't work.  I changed the path/copied the binary over to `/usr/local/bin`, updated the systemd service file to the new path, and everything worked.

Is there a reason for the `.local` path?  Could you install instead to `/usr/local/bin`?

### Logs

```bash
May 04 22:25:07 test systemd[1]: lnxlink.service: Scheduled restart job, restart counter is at 76.
May 04 22:25:07 test systemd[1]: Started lnxlink.service - LNXlink.
May 04 22:25:07 test systemd[1]: lnxlink.service: Main process exited, code=exited, status=203/EXEC
May 04 22:25:07 test systemd[1]: lnxlink.service: Failed with result 'exit-code'.
```

**Comment by answer35** [comment]
Hi, I also have the issue that lnxlink start properly with terminal but no way to have it working with systemd. I am running Fedora 41. Can you explain what you did exactly to have it working on your system please ?

**Comment by FuzzyMistborn** [comment]
>I changed the path/copied the binary over to /usr/local/bin, updated the systemd service file to the new path, and everything worked.

This is what I did.  Alternatively, you can use `restorecon -Rv` along with the path, so `restorecon -Rv $HOME/.local/bin/`.  May need sudo, not sure.

**Comment by answer35** [comment]
How did you filled the service file so it can start. I can't make it to work

**Comment by FuzzyMistborn** [comment]
You change the path in the service file to where you put the binary file `lnxlink` and then you do a systemd daemon-reload.  Then start up the systemd service.
