### ISSUE TITLE
Request: Binary sensors for Bash `expose` commands

### ISSUE THREAD

**Issue by jeremysherriff** [bkbilly/lnxlink#112]
### Describe the solution you'd like

I would like to be able to create arbitrary `binary_sensor` types, in addition to creating sensors.

LNXLink would need to parse the command responses to interpret various values as `true` or `false` as appropriate;
- 0 or 1
- true or false
- True or False
- 0 or any other int32 value
- yes or no
- any string value vs ""

### Additional context

It is likely that python's built-in type-casting would suffice to translate values to boolean equivalents.

**Comment by bkbilly** [comment]
This is quite a big spectrum of types to convert to boolean which might overlap with each other.

My idea whould be to set the output as `false` if it's in the values `"false", "no", "0", ""` and all the others to `true`.
You can check this implementation that I am talking about:
```python
stdin = "1"
output = stdin.lower() not in ["false", "no", "0", ""]
print(output)
````

Let me know what you think of this.

**Comment by jeremysherriff** [comment]
Yes that sounds great.
I've noticed with some native integrations, binary sensors include an attribute to indicate what the raw value was, in case of mis-interpretation which might be a good idea. Example for a LocalTuya switch:
![image](https://github.com/bkbilly/lnxlink/assets/1082213/f3df615e-f17f-4306-a22f-5f52defeaac3)

**Comment by bkbilly** [comment]
I've added support for binary sensors with an attribute Raw that shows the actual value of that sensor.
