### ISSUE TITLE
Flatpak install, nothing happens when launched / cant find config.yaml

### ISSUE THREAD

**Issue by cromelex** [bkbilly/lnxlink#125]
### What type of installation are you running?

Desktop

### Which Linux OS are you using?

aurora-dx-stable

### Which version of LNXLink has the issue?

https://flathub.org/apps/io.github.bkbilly.lnxlink

### Describe the problem

I have tried installing lnxlink via the flatpak, as using docker I couldn't get it working for the mic and webcam used status.

The install seems to go through, but there is no action when I click launch and no detailed instructions - I'd assume I would still need to do the config, but I can't find a config.yaml created by this install.

**Comment by bkbilly** [comment]
The flatpak is very new addition, so I didn't have the time to write documentation for it.
You will need to run it with the `-ic` option and the config path should be under the documents directory.
`-ic ~/Documents/config.yaml`

Keep in mind that it won't create a systemd service, so you might want to create one manually.

**Comment by cromelex** [comment]
Cheers, I'll give it a try tomorrow and report back.

**Comment by cromelex** [comment]
Thanks, this worked and I managed to get it working

I created a systemd service manually to make sure it starts on boot.

**Comment by bkbilly** [comment]
That's great!
I am currently trying to release a new version that runs without any arguments and sets the default path to `~/Documents/lnxlink.yaml`

**Comment by cromelex** [comment]
> That's great! I am currently trying to release a new version that runs without any arguments and sets the default path to `~/Documents/lnxlink.yaml`

Could I suggest using a LNXlink folder?

`~/Documents/LNXlink/config.yaml` or so? Just neater in my opinion.

Happy to test any new release and give feedback.

Thanks.

**Comment by bkbilly** [comment]
That's a good idea.
I am still figuring out how to make a flatpak release update, so I don't know when I'll have it done.

**Comment by bkbilly** [comment]
I updated the flatpak package with the latest updates and it works with a default config file you suggested.
I've also added support for docker and systemd, but I am not sure if the systemd works on all systems.
There are more modules that still don't work with flatpak, but fortunately the most important ones work as expected.

**Comment by cromelex** [comment]
I will give it a try next week. 
Thanks

**Comment by cromelex** [comment]
Hi,

Just tried this, and checked the new [documentation for flatpak install](https://bkbilly.gitbook.io/lnxlink/setup) to make sure I wasn't missing anything.

I uninstalled the previous version first (and disabled the systemd service I had created before etc to avoid any weirdness).

Whenever I try to run I get an error:

> flatpak run io.github.bkbilly.lnxlink
> bwrap: Can't make symlink at /var/run: File exists

Thanks

**Comment by bkbilly** [comment]
I can't think of any reason why you get this error.
The `/var/run/` directory is only used for the files `/var/run/reboot-required` and `/var/run/docker.sock`, but even if these files don't exist, I don't get any errors.

**Comment by cromelex** [comment]
I have a `/var/run/docker.sock` but no `/var/run/reboot-required`.

I did not have any error with the previous version

**Comment by bkbilly** [comment]
You could try installing the latest version to check if you still got this issue.

**Comment by cromelex** [comment]
I'm away for a bit but I'll give this a try next week and report back. 
Thanks

**Comment by cromelex** [comment]
> You could try installing the latest version to check if you still got this issue.

With the latest flatpack I am getting the following error:

> ❯ flatpak run io.github.bkbilly.lnxlink
> bwrap: Can't make symlink at /var/run: existing destination is ../run

**Comment by Willdrick** [comment]
is there any way to manually change the default location for the flatpak install method? Otherwise could I suggest to use $XDG_DOCUMENTS_DIR instead of a hardcoded path?
