### ISSUE TITLE
Changing systemctl service requires sudo

### ISSUE THREAD

**Issue by Hoseasack** [bkbilly/lnxlink#130]
### What type of installation are you running?

Desktop

### Which Linux OS are you using?

ZorinOS 17.2 Core

### Which version of LNXLink has the issue?

2024.10.0

### Description

I have a custom service setup for running a crypto miner on my PC. The service works both via command line and via Home Assistant. The issues however is when enabling or disabling the service on HA prompts the user for their password on the physical computer, as the service requires sudo to do so. I tried the added bit to allow lnxlink to run as sudo but nothing helps. `cole ALL=(ALL) NOPASSWD: /usr/sbin/grub-reboot`

I also tried creating an exception for the service but nothing. 
`cole ALL=(ALL) NOPASSWD: /usr/sbin/grub-reboot, /usr/bin/systemctl start miner.service, /usr/bin/systemctl stop mminer.service`

Any help would be appreciated!

**Comment by bkbilly** [comment]
You could check the logs for any issues when you start or stop a service. These are located at the same location as your configuration under the name `lnxlink.log`

**Comment by Hoseasack** [comment]
There are no errors pertaining to services. Just errors from Bluetooth devices not connected.
