### ISSUE TITLE
Fedora KDE Dbus problem

### ISSUE THREAD

**Issue by CodingGhost** [bkbilly/lnxlink#132]
### What type of installation are you running?

Desktop

### Which Linux OS are you using?

Fedora 40

### Which version of LNXLink has the issue?

2024.10.1

### The problem

Hello,
Im trying to use the notifications with lnxlink but it wont work because there are Dbus errors. Im assuming that this is because Im using KDE and not gnome maybe?
Is there any workaround for that?

### Logs

INFO:lnxlink:LNXlink 2024.10.1, Python 3.12.5
ERROR:lnxlink:Can't import package dasbus: No module named 'gi'
ERROR:lnxlink:Can't use DBus for system monitor
.
.
.
INFO:lnxlink:Message received notify: b'{ "title": "Notification Title",\n  "message": "Testing notification",\n  "urgency": "normal",\n  "timeout": 1000,\n  "buttons": ["Open Image"] }'
ERROR:lnxlink:Couldn't run command for module <lnxlink.modules.notify.Addon object at 0x7fae32b0c1d0>: 'NoneType' object has no attribute 'DBusNotification', Traceback (most recent call last):
  File "/home/jonas/.local/share/pipx/venvs/lnxlink/lib64/python3.12/site-packages/lnxlink/__main__.py", line 327, in on_message
    result = addon.start_control(select_service, message)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jonas/.local/share/pipx/venvs/lnxlink/lib64/python3.12/site-packages/lnxlink/modules/notify.py", line 66, in start_control
    self.notify = self.lib["notify"].DBusNotification(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'DBusNotification'

**Comment by bkbilly** [comment]
It should work on KDE the same way as with Debian.
Make sure you have these packages installed and try running it again:
```
patchelf meson libdbus-glib-1-dev libglib2.0-dev libcairo2-dev libgirepository1.0-dev
```

**Comment by CodingGhost** [comment]
I checked these, and because im on fedora the package names are a little different but I think I have all these. Also 
dbus-notification -t hello -m world 
is working. But I still get these errors.

**Comment by bkbilly** [comment]
Hi, sorry for the long delay, but I didn't have time lately to find the issue.
I tried on a VM the **Fedora KDE Plasma Desktop 41** and I found that you need to install these packages:
```bash
sudo dnf install -y dbus-glib-devel glib2-devel cairo-devel gobject-introspection-devel python3-gobject-devel cairo-gobject-devel alsa-lib-devel portaudio-devel
```
I hope it works for you too.
