### ISSUE TITLE
Service seems to stop after a few hours 

### ISSUE THREAD

**Issue by Daniel-dev22** [bkbilly/lnxlink#14]
I am the one with the nuc issue yesterday.

I noticed the service stopped running and I restarted it. It started working as expected and suddenly died again, 6 hours ago. I know something happened as the home assistant sensors are unavailable and they all went unavailable at the same time. Is there a way to access the logs and potentially see what happened before it failed?

**Comment by bkbilly** [comment]
Saving the logs is a feature I haven't implemented yet, though you might be able to check it when it dies.

This might help:
```bash
systemctl --user status lnxlink.service
```

**Comment by bkbilly** [comment]
it seems that it is running for only 2 seconds. 
This might happen if it starts and stops all the time, so keep in mind when it started.
You can check this with this command:
```bash
grep 'Started LNXLink' /var/log/syslog
```

You can try running it manually as I mentioned here https://github.com/bkbilly/lnxlink/issues/13#issuecomment-1180794120 to check if it stops for any reason.

I will update the app so that it will show the logging on a file.

**Comment by bkbilly** [comment]
The 1st one is perfect :)

Try like yesterday to remove the file send_keys.py and the send-keys from the config.

**Comment by bkbilly** [comment]
oh, the logs you sent me are from yesterday's runs.

Try running it like this so that it will only show you the last 100 lines:
```bash
journalctl --user -u lnxlink -n 100 --no-pager
```

**Comment by bkbilly** [comment]
I've just pushed an update which is has more prints and it contains the restart autoconfig.
Follow these instructions:
```bash
cd /opt/lnxlink/
git stash
git pull
systemctl --user restart lnxlink.service
```

If you still see a lot of restarts using this:
```bash
grep 'Started LNXLink' /var/log/syslog
```

Then send me the logs:
```bash
journalctl --user -u lnxlink -n 100 --no-pager
```

**Comment by bkbilly** [comment]
That's a problem with the send_keys.py. 
WIth the update the files you deleted have been reverted back, so try removing it and trying again.

**Comment by bkbilly** [comment]
You might be right about the ssh session. 
You can try installing it as a system service of the root user. 

You need to create a file `/etc/systemd/system/lnxlink.service` and write this:
```desktop
[Unit]
Description=LNXLink
After=network-online.target

[Service]
Type=simple
Restart=always
User=root
WorkingDirectory=/opt/lnxlink
ExecStart=/usr/bin/python3 /opt/lnxlink/run.py

[Install]
WantedBy=default.target
```

And then disable the user service and enable the system service:
```shell
systemctl --user stop lnxlink.service
systemctl --user disable lnxlink.service
sudo systemctl enable lnxlink.service
sudo systemctl start lnxlink.service
```

**Comment by bkbilly** [comment]
You can freely change the `User=root` to the one you want.

It seems that you need to run it as a system service and not as a user service.
I don't fully understand why the user service doesn't work, but for the desktop it works great.

I hope this time we fixed the problem.

**Comment by bkbilly** [comment]
Seems that this issue has been resolved so I am closing it.
If you still have problems you can reopen it or create a new one.

**Comment by Tekno-man** [comment]
I know this was closed by I have been having the same issue so will try running it as a root service instead also

**Comment by Tekno-man** [comment]
This seemed to fix the issue of the service stopping but do I need to modify something so that the service will start on boot?

**Comment by bkbilly** [comment]
All you need to do is follow the instructions on this comment to run on boot. 
https://github.com/bkbilly/lnxlink/issues/14#issuecomment-1186438275

**Comment by Tekno-man** [comment]
Thanks so much. Appreciate the help.
