### ISSUE TITLE
Installation error on Ubuntu 22.04 with pip3

### ISSUE THREAD

**Issue by andenbeere** [bkbilly/lnxlink#24]
Hello there,

your project looks interesting and I'd like to try it out, but can't finish the installation. I install as per your instructions with `pip3 install -U lnxlink`. The problem then seems to be about compiling the dbus dependency. See the attached logs for more details: [lnxlink_installation.log](https://github.com/bkbilly/lnxlink/files/9899751/lnxlink_installation.log).

Thank you for your time.

**Comment by bkbilly** [comment]
I think you are right about the dbus dependency.
You could try installing this before the installation of lnxlink:
```bash
sudo apt install patchelf
```

**Comment by bkbilly** [comment]
Another solution is installing these dependencies:
```bash
sudo apt install libdbus-glib-1-dev libdbus-1-dev
```

**Comment by andenbeere** [comment]
That did the trick, patchelf had been missing. Installation worked from there on. Now I can play with lnxlink.

Thank you!

**Comment by koulis-probotek** [comment]
You are most welcome!

**Comment by bkbilly** [comment]
You are most welcome!
