### ISSUE TITLE
Idle module - no mutter module

### ISSUE THREAD

**Issue by Dinth** [bkbilly/lnxlink#26]
**Describe the problem**
Hi. I have just upgraded lnxlink from 2022.10.? to 2022.11.2 and run into an issue when configuring everything via "lnxlink -c config.yaml".

```
Successfully loaded addon: shutdown
Successfully loaded addon: restart
Successfully loaded addon: send_keys
Successfully loaded addon: notify
Successfully loaded addon: cpu
Successfully loaded addon: memory
Successfully loaded addon: network_upload
Successfully loaded addon: network_download
Successfully loaded addon: media
Successfully loaded addon: microphone
Successfully loaded addon: idle
Successfully loaded addon: bluetooth_battery
Successfully loaded addon: screen_onoff
Connected to MQTT with code 0
Can't load addon: idle
Traceback (most recent call last):
  File "/home/dinth/.local/lib/python3.10/site-packages/lnxlink/__main__.py", line 54, in monitor_run
    pub_data = addon.getInfo()
  File "/home/dinth/.local/lib/python3.10/site-packages/lnxlink/modules/idle.py", line 11, in getInfo
    idle_sec = monitor.get_idle_time()
  File "/usr/local/lib/python3.10/dist-packages/idle_time/__init__.py", line 87, in get_idle_time
    reply = self.connection.send_and_get_reply(self.message)
  File "/usr/local/lib/python3.10/dist-packages/jeepney/integrate/blocking.py", line 78, in send_and_get_reply
    return future.result()
  File "/usr/local/lib/python3.10/dist-packages/jeepney/integrate/blocking.py", line 33, in result
    raise value
jeepney.wrappers.DBusErrorResponse: [org.freedesktop.DBus.Error.ServiceUnknown] ('The name org.gnome.Mutter.IdleMonitor was not provided by any .service files',)
Can't load addon: idle
```
The above error keeps repeating itself.

**Desktop (please complete the following information):**
 - OS: [e.g. Ubuntu 22.04] Mint 21
 - Version [e.g. 2022.10.3] 2022.11.2

**Additional context**
I think that i managed to sort it out by removing "idle" module from the config file, but it would be nice to have this error handled in a better way, especially if idle module is enabled by default.

**Comment by bkbilly** [comment]
I've created a feature request for Linux Mint for the package idle_time that I am using: https://github.com/escaped/idle_time/issues/7

**Comment by bkbilly** [comment]
Now it should be working, but you will need to install it manually from my git repository.
```bash
pip3 uninstall idle_time
pip3 install 'idle_time @ git+https://github.com/bkbilly/idle_time.git'
systemctl --user restart lnxlink.service
```
We will have to wait for @escaped to create a new release (v0.2.0) in order to be able to install it normally, but for now it will work with the instructions I mentioned.
Let me know if it works for you.

**Comment by bkbilly** [comment]
@Dinth 
Have you tried it with the instructions I mentioned above?

**Comment by Dinth** [comment]
Not really, sorry, i am running headless mode and needed to disable this and a couple of other modules. Im going to close this for now but will try again once idle_time gets updated.

**Comment by Iceman248** [comment]
Any chance this will work on Arch based Linux distros?

**Comment by bkbilly** [comment]
Have you tried the instructions I mentioned above?
They are also mentioned on Readme FAQ section

**Comment by Iceman248** [comment]
I forgot to mention why I asked, sorry. I don't use Gnome. I use KDE Plasma.

**Comment by bkbilly** [comment]
I don't have KDE, so I am going to need some info from you.
There are some apps that can browse the dbus, for Ubuntu I am using qdbus.
What I need you to send me, the idle path like so:
```bash
bkbilly@pc:~$ qdbus | grep -i idle
 org.gnome.Mutter.IdleMonitor
```

**Comment by bkbilly** [comment]
Also send me the result from this command:
```bash
pip3.9 freeze | grep idle
```

**Comment by Iceman248** [comment]
I don't get any response from `qdbus | grep -i idle`

`pip3 freeze | grep idle` gives me `idle-time==0.1.0`

**Comment by bkbilly** [comment]
I am afraid that it might not be working on your system...

You can try installing the the correct version of idle-time by follow the instructions [I mention above](https://github.com/bkbilly/lnxlink/issues/26#issuecomment-1304554354) or on the [FAQ section](https://github.com/bkbilly/lnxlink#idle-time-not-working).
Once installed correctly you can try it yourself like so:
```bash
sleep 3 && python3.8 -m idle_time
```

**Comment by bkbilly** [comment]
Unfortunately it is not supported by the idle-time package that I am using.
I am not very familiar with the KDE environment, but if you can find any command that gets the idle time, I can add it to LNXLink.

An alternative that I was thinking is the `xprintidle`.
Check it out and let me know.

**Comment by Iceman248** [comment]
That does print out the ms of time, mostly 8, one time 9. I am running it on the system, so seems to take that long to get time after I press enter.
