### ISSUE TITLE
Systemctl config generated incorrectly?

### ISSUE THREAD

**Issue by Dinth** [bkbilly/lnxlink#27]
**Describe the problem**
It seems that if during the initial configuration i choose to create a system-wide start-up script (i dont remember how exactly it was worded, but it was one of the first questions), lnxlink generates a systemctl config pointing to lnxlink at /usr/local/bin/lnxlink, but the lnxlink is still located in user's home folder, therefore lnxlink doesnt start. 

**Desktop (please complete the following information):**
 - OS: [e.g. Ubuntu 22.04] Mint 21
 - Version [e.g. 2022.10.3] 2022.11.2

**Logs**
```txt
dinth@dinth-desktop-linux:~$ systemctl status lnxlink
× lnxlink.service - LNXLink
     Loaded: loaded (/etc/systemd/system/lnxlink.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Sat 2022-11-05 11:40:56 GMT; 5h 0min ago
    Process: 1640 ExecStart=**/usr/local/bin/lnxlink** -c /home/dinth/config.yaml (code=exited, status=203/EXEC)
   Main PID: 1640 (code=exited, status=203/EXEC)
        CPU: 518us

Nov 05 11:40:56 dinth-desktop-linux systemd[1]: lnxlink.service: Scheduled restart job, restart counter is at 5.
Nov 05 11:40:56 dinth-desktop-linux systemd[1]: Stopped LNXLink.
Nov 05 11:40:56 dinth-desktop-linux systemd[1]: lnxlink.service: Start request repeated too quickly.
Nov 05 11:40:56 dinth-desktop-linux systemd[1]: lnxlink.service: Failed with result 'exit-code'.
Nov 05 11:40:56 dinth-desktop-linux systemd[1]: Failed to start LNXLink.

dinth@dinth-desktop-linux:~$ whereis lnxlink
**lnxlink: /home/dinth/.local/bin/lnxlink**
```

**Comment by bkbilly** [comment]
I haven't mentioned this on the install script, but if you want to use it as a system service, you will need to install lnxlink as a super user (sudo).
My recommendation for installing it on a desktop environment is to do it without sudo and when it asks for `Install as a user service? (True/False) [True]:`, you leave the default which is `True`.
You can follow these instructions to install it from scratch:
```bash
sudo systemctrl stop lnxlink.service
sudo systemctrl disable lnxlink.service
sudo pip3 uninstall lnxlink
pip3 install lnxlink
lnxlink -c /your/config.yaml
# Answer True when asks for installing as a user service
```
If you want it as a headless setup then do this:
```bash
systemctrl --user stop lnxlink.service
systemctrl --user disable lnxlink.service
pip3 uninstall lnxlink
sudo pip3 install lnxlink
sudo lnxlink -c /your/config.yaml
# Answer False when asks for installing as a user service
```

I know it's a bit complicated to install, but I wanted to be able to add support for Headless installations.

**Comment by Dinth** [comment]
Thanks! It worked. Would it be possible to add this to documentation?

**Comment by bkbilly** [comment]
Yeah, you are right. I will update it.
