### ISSUE TITLE
Open Path/URL

### ISSUE THREAD

**Issue by Iceman248** [bkbilly/lnxlink#28]
Could you possibly add the ability to open paths and URLs? Thanks.

**Comment by bkbilly** [comment]
Do you mean opening them with the default app?
I found this tool that will do exactly that for URL and files:
```bash
xdg-open myimg.jpeg
xdg-open https://www.google.com
```

**Comment by Iceman248** [comment]
Yes, please.

**Comment by bkbilly** [comment]
I've added this feature and some instructions that might make some things more clear.
Soon it will be uploaded as a pip package with version `2022.11.3`.

**Comment by Iceman248** [comment]
Thanks, will try it out. I was hung up on why send-keys wasn't working and figured I should try it with an underscore instead of a hyphen and it worked. There is a typo on the main page for that command.

**Comment by Iceman248** [comment]
I cannot get the xdg-open to work, hyphen or underscore, all I see is JSON format could not be converted or something along those lines.

**Comment by bkbilly** [comment]
Thanks for pointing out the send-keys problem. I will fix it...

I have an absolute path for running the xdg-open command which might be a problem.
Let me know which one is the path:
```bash
which xdg-open
```

**Comment by Iceman248** [comment]
/usr/bin/xdg-open

**Comment by Iceman248** [comment]
Also, I noticed that sometimes send_keys seems to double tap or hold down the second key too long. I was testing with <CTRL>+w to close a browser tab and sometimes it would close 2 tabs.

**Comment by bkbilly** [comment]
You will have to enable `xdg_open` on your config in order to make it work and then restart lnxlink.

**Comment by bkbilly** [comment]
I've tried running the send_keys command with "<CTRL>+t", but it only run once.
I don't know why you have this problem...

**Comment by Iceman248** [comment]
How do I enable it in my config? I did try adding it as a line item below the other ones, but I don't think I actually restarted it when I was testing it that way.

Sometimes it has only done it once, in fact I think most times overall it has been once, but it has been close to 50% of the time it's been twice and one time might have been three times.

**Comment by Iceman248** [comment]
I tried adding it, but I just get this.

`ModuleNotFoundError: No module named 'lnxlink.modules.xdg_open'`

**Comment by bkbilly** [comment]
You must be running the latest version of lnxlink `2022.11.3`.
You can find the installed version from home assistant.
If it's not the latest version, then do this:
`pip3 install -U lnxlink` and restart it.

**Comment by Iceman248** [comment]
I already was up to date, I even went as far as reinstalling it and even redoing the config from scratch. I can see the xdg_open module inside the modules folder.
