### ISSUE TITLE
Service keeps crashing

### ISSUE THREAD

**Issue by Blockmaster2706** [bkbilly/lnxlink#3]
Whenever i try to start the lnxlink service it crashes. 

running " systemctl --user status lnxlink " returns the following:

lnxlink.service - LNXLink
     Loaded: loaded (/home/leon/.config/systemd/user/lnxlink.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Mon 2022-01-03 20:35:10 CET; 43s ago
    Process: 5666 ExecStart=/usr/bin/python3 /opt/lnxlink/run.py (code=exited, status=1/FAILURE)
   Main PID: 5666 (code=exited, status=1/FAILURE)

Jan 03 20:35:10 leon-KDE systemd[3520]: lnxlink.service: Scheduled restart job, restart counter is at 6.
Jan 03 20:35:10 leon-KDE systemd[3520]: Stopped LNXLink.
Jan 03 20:35:10 leon-KDE systemd[3520]: lnxlink.service: Start request repeated too quickly.
Jan 03 20:35:10 leon-KDE systemd[3520]: lnxlink.service: Failed with result 'exit-code'.
Jan 03 20:35:10 leon-KDE systemd[3520]: Failed to start LNXLink.

**Comment by bkbilly** [comment]
Try running the app manually.
Firstly stop the service:
```
systemctl --user stop lnxlink.service
```
Then run the app like so and send me the output to debug it:
```
/usr/bin/python3 /opt/lnxlink/run.py
```

**Comment by Blockmaster2706** [comment]
Done what you told me to do.

Here is the output:

`Traceback (most recent call last):
  File "/opt/lnxlink/run.py", line 200, in <module>
    lnxlink = LNXlink('config.yaml')
  File "/opt/lnxlink/run.py", line 29, in __init__
    self.config = self.read_config(config_path)
  File "/opt/lnxlink/run.py", line 66, in read_config
    with open(config_path) as file:
FileNotFoundError: [Errno 2] No such file or directory: 'config.yaml'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 153, in apport_excepthook
    with os.fdopen(os.open(pr_filename,
FileNotFoundError: [Errno 2] No such file or directory: '/var/crash/_opt_lnxlink_run.py.1000.crash'

Original exception was:
Traceback (most recent call last):
  File "/opt/lnxlink/run.py", line 200, in <module>
    lnxlink = LNXlink('config.yaml')
  File "/opt/lnxlink/run.py", line 29, in __init__
    self.config = self.read_config(config_path)
  File "/opt/lnxlink/run.py", line 66, in read_config
    with open(config_path) as file:
FileNotFoundError: [Errno 2] No such file or directory: 'config.yaml'
`

**Comment by bkbilly** [comment]
Oh, my bad, forgot to tell you about an other command for changing directory.
Try running the bellow commands and send me the output:
```bash
systemctl --user stop lnxlink.service
cd /opt/lnxlink
/usr/bin/python3 /opt/lnxlink/run.py
```

**Comment by bkbilly** [comment]
To solve this you need to create the config.yaml manually or like so:
```
cp /opt/lnxlink/config_temp.yaml /opt/lnxlink/config.yaml
```

This is done automatically with the installation script `install.sh` which is my recommended way of installing lnxlink because it installs all dependencies.

**Comment by Blockmaster2706** [comment]
I'm actually pretty sure that i ran that Script to install it because i ran your "1 command install" method. Maybe you should check if there is something wrong with the script? Anyways, i manually created that file now and it seems the service is now no longer crashing and it looks like it is working. Thanks

**Comment by bkbilly** [comment]
I am happy that it works for you and I hope you find it useful.
I'll check what went wrong with my script and I will update accordingly.
