### ISSUE TITLE
Computer as a smart TV

### ISSUE THREAD

**Issue by Juanipis** [bkbilly/lnxlink#31]
I think if the computer is a dummy tv for home assistant could be better because the Google home app recognize it like one device and not multiple switches.

In the technical notes the repo describe how to make a custom sensor but I didn't find a way to make this.

**Comment by bkbilly** [comment]
If you mean for the media_player, it is not supported with MQTT discovery, so I am not able to add it automatically like the other integrations.
To add it, you will have to follow the instructions on this thread:
https://github.com/bkbilly/hass-mqtt-mediaplayer

**Comment by bkbilly** [comment]
I've updated the hass-mqtt-mediaplayer so that you can install it from HACS.

**Comment by Juanipis** [comment]
Thanks for this, i'ts very usseful
