### ISSUE TITLE
Expose Stat Send Interval to Config

### ISSUE THREAD

**Issue by izzeho** [bkbilly/lnxlink#32]
Have been playing with this tool and it's pretty handy. Worked out of the box on most devices. I've turned off most of the stats for most client devices, as it's pretty noisy. I had a brief look at the timer and the interval is 5 seconds, is it possible to expose this as an optional setting in the config?

Plenty of functions in linux to get CPU averages over X period as well, I didn't dig to see if the CPU usage now is instantaneous or average.

**Comment by bkbilly** [comment]
That's a good idea to make it configurable.
I am going to change this on the first change I get.
This is the code that is responsible for the timer:
https://github.com/bkbilly/lnxlink/blob/master/lnxlink/__main__.py#L72

**Comment by bkbilly** [comment]
I've exposed it to the config as an `update_interval`.
The default is 5 seconds if it doesn't exist on the config file, which means that you have to write it yourself.
