### ISSUE TITLE
TTS Playback on LNX link Device

### ISSUE THREAD

**Issue by Iceman248** [bkbilly/lnxlink#34]
**Describe the solution you'd like**
The ability to play TTS on a LNX link device. I tried to use Browser Mod, but across several different computers of different operating systems, the media player portion doesn't work at all. I haven't gotten any help from that project, so I've just about given up on it working for me in that way. This seems close, just not able to play TTS.

**Additional context**
I couldn't figure out how to play media, only pause/play, although not sure if I would use for actual media playback or not.

**Comment by bkbilly** [comment]
I have updated the [mqtt-mediaplayer](https://github.com/bkbilly/hass-mqtt-mediaplayer) with the option to play_media which includes TTS, media_player.play_media and anything related.
As for playing the media on lnxlink the `cvlc` app could be used which supports images, video, video stream, mp3.
I will let you know when I update it with this functionality.

**Comment by Iceman248** [comment]
Thanks. Can you give me an example of how to use it though for TTS. I could not figure it out. I added in the new play_media line and updated.

**Comment by bkbilly** [comment]
The LNXLink still doesn't support the play_media, you will have to wait, but you can test it by checking the mqtt commands.

Here is an example of the TTS service call:
```yaml
service: tts.google_say
data:
  entity_id: media_player.desktop_linux
  message: Hello world!
```

And the result on the MQTT side:
```json
{
  "media_type": "audio/mpeg", 
  "media_id": "http://192.168.1.2:8123/api/tts_proxy/1341b19136178w6bc42212s385fa09447x8_en_-_google_translate.mp3"
}
```

**Comment by Iceman248** [comment]
Okay, I do see that. I misunderstood the last part of your previous post. Thanks.

**Comment by bkbilly** [comment]
I've just updated LNXLink to version 2023.1.1 which supports media_play.
It will take a few minutes to get updated on PyPi, so be patient. 

Keep in mind that I've also changed the mqtt-mediaplayer from `/media/playmedia` to `/media/play_media`

**Comment by Iceman248** [comment]
Thanks, works great!
