### ISSUE TITLE
Add xprintidle as idle time option

### ISSUE THREAD

**Issue by Iceman248** [bkbilly/lnxlink#35]
**Describe the solution you'd like**
The ability to use xprintidle to track idle time.

**Comment by bkbilly** [comment]
I've created a new release `2023.1.2` which only depends on `xprintidle`.
Let me know if you have any issues.

**Comment by Iceman248** [comment]
Works fine, thanks.

**Comment by Iceman248** [comment]
I haven't been able to find an alternative for xprintidle on Wayland. It looks like it doesn't work on it.
