### ISSUE TITLE
Feature request: System Restart Required (sensor)

### ISSUE THREAD

**Issue by ocean75** [bkbilly/lnxlink#36]
**Describe the solution you'd like**
Add new sensor to Home Assistant that indicate if a 'System restart is required'.

**Additional context**
cat /var/run/reboot-required (*** System restart required ***) or via script?

**Comment by bkbilly** [comment]
I don't seem to find the file `/var/run/reboot-required` on my system.
When is it created and on which occasions does linux need restart?
Most recent versions don't need restart even after a kernel update...

**Comment by ocean75** [comment]
Hi, 

Awesome product!!!
I am running Ubuntu 22.04 on several machines and the message show up if a restart is required. Not entirely sure what causes the message to appear, but it must be some sort of update.

If the file /var/run/reboot-required exists, you'll get the message. If a restart isn't required the file wont exist. 
```bash
cat /var/run/reboot-required
```
There might be other ways creating such a sensor as well?

![How-do-I-know-if-my-ubuntu-server-needs-a-restart](https://user-images.githubusercontent.com/81304084/213298009-b3ff9b26-2461-498a-a998-82ed6a70f03e.png)

**Comment by bkbilly** [comment]
I've created a new release `2023.1.2` which should support the new sensor.
I haven't tested it, so just let me know if it works.

**Comment by ocean75** [comment]
Hello,

From what I can tell, it appears to be working perfectly. I tested on a VM that require a restart, and one that didn't. That is awesome. Thank you.

![image](https://user-images.githubusercontent.com/81304084/213879243-df996e11-8744-4712-846c-6ac7e1ff75b1.png)
