### ISSUE TITLE
Feature Request: Disk Usage

### ISSUE THREAD

**Issue by n1md4** [bkbilly/lnxlink#37]
Something equivalent to the following:

**Filesystem**
```
~> df -hT | grep -v 'Filesystem' | grep -v tmpfs | awk '{ print $1 }'
/dev/mapper/laptop-vg-root
/dev/nvme0n1p2
/dev/nvme0n1p1
```

**Size**
```
~> df -hT | grep -v 'Filesystem' | grep -v tmpfs | awk '{ print $3 }'
186G
471M
511M
```

**Used**
```
~> df -hT | grep -v 'Filesystem' | grep -v tmpfs | awk '{ print $4 }'
124G
231M
5.8M
```

**Avail**
```
~> df -hT | grep -v 'Filesystem' | grep -v tmpfs | awk '{ print $5 }'
52G
216M
506M
```

**Use%**
```
~> df -hT | grep -v 'Filesystem' | grep -v tmpfs | awk '{ print $6 }'
71%
52%
2%
```

**Comment by n1md4** [comment]
This example page from psutil.readthedocs.io looks useful: https://github.com/giampaolo/psutil/blob/master/scripts/disk_usage.py

I'd submit a PR but I'm no coder!

**Comment by bkbilly** [comment]
That sounds great!

**Comment by bkbilly** [comment]
I was thinking about your feature request, and currently lnxlink only supports exposing only a single sensor.
The others can only be exposed as attributes.
You can take a look at the getInfo from media.py.

**Comment by n1md4** [comment]
I suppose '/' would make the most sense.

**Comment by bkbilly** [comment]
I think that it would be best to have all the disks as attributes and on the status attribute add a true or false if one of the devices is more than 90%.
Here is an example of a dict:
```json
{
  "status": false,
  "size /dev/mapper/laptop-vg-root": 186000,
  "used /dev/mapper/laptop-vg-root": 124000,
  "available /dev/mapper/laptop-vg-root": 506000,
  "used /dev/mapper/laptop-vg-root": 71,
  "size /dev/nvme0n1p2": 471,
  .
  .
  .
}
```

**Comment by bkbilly** [comment]
I've added the support on the new release of LNXlink: `2023.1.3`.
