### ISSUE TITLE
install problem

### ISSUE THREAD

**Issue by renarena** [bkbilly/lnxlink#39]
onDebian (LMDE 5) i installed  dependencies. 
`pip3 install -U lnxlink` doesnt work, but `python3 -m pip install -U lnxlink`.

but then i have errors:
```
$ python3 lnxlink -c config.yaml
python3: can't open file '/home/xxx/lnxlink': [Errno 2] No such file or directory
```
what can i do?

**Comment by bkbilly** [comment]
That is not the correct way to run it.
You have added the python3 before lnxlink which is wrong.
Once installed a new command is created called `lnxlink` which is located `/home/xxx/.local/bin/lnxlink`.
If you run it without python3, it should be working fine.

**Comment by renarena** [comment]
I added python3 because it was not working. Searched for it in .local/lib/python3.9/site-packages.
I found it now and called it with path.
After creating the config and changing the paths in it manually it seems no to work.

But nothing happens on mqtt.  I can login using mqttExplorer as user lnxlink.
Du i need to install something else for mqtt?

**Comment by bkbilly** [comment]
After the config is created, you need to edit it and restart lnxlink.
Please send me the command you are using to run the app and the logs that it shows.

**Comment by bkbilly** [comment]
It seems that the service keeps crashing.
Send me the latest logs using this command:
```bash
journalctl --user -u lnxlink -n 300 --no-pager
```

**Comment by renarena** [comment]
oh, silly me - wrong IP address, missed number due to bad working key.
```
Feb 06 17:15:39 xxx lnxlink[1205605]: OSError: [Errno 101] Network is unreachable
Feb 06 17:15:39 xxx systemd[2029]: lnxlink.service: Main process exited, code=exited, status=1/FAILURE
```
Now its working. But whats the meaning of  bluetooth_battery 55% on a Desktop PC without bluetooth? :-)

**Comment by bkbilly** [comment]
That's a great question!
For bluetooth battery I am getting the information from this command:
```
upower --dump | grep percentage
```

Maybe it's the laptop battery?
If you find out, please let me know.

**Comment by renarena** [comment]
Its a Desktop PC, no batteries there. I cannot see the connection between BT and Battery, even in Laptops.
```
$ upower --dump | grep percentage
    percentage:          55% (should be ignored)
    percentage:          55% (should be ignored)
```

**Comment by bkbilly** [comment]
I am not fully familiar with the upower command, but from my understanding it shows any device with battery and it's status. This includes bluetooth devices and laptop battery.
To fully understand what these values are you should run it without the grep:
```
upower --dump
```
In your case which is a desktop pc without any bluetooth device, you should remove it from your config or disable it on home assistant.

**Comment by renarena** [comment]
The  lines belong to keyboard and mouse (both wired).
Maybe you can test for the "(should be ignored)". 
I have commented out the batterie modul :-)
