### ISSUE TITLE
[Feature Request] add toggle monitor 

### ISSUE THREAD

**Issue by thundergreen** [bkbilly/lnxlink#4]
Hello I like the idea ..at the moment at the moment I use a mqtr solution to turn on and off my screen.its used for my magic mirror in the toilette.but unfortunately somehow I have to start it manually die to python skills not good. Is there a way to add monitor on off ?

**Comment by bkbilly** [comment]
This is a nice idea for how you can use my app.
I believe that you are able to do this without any update on my part, though I will look into it.
You can map the screen on/off with a keyboard shortcut and then use the Send-Keys command to activate the key map.

This is an example:
**Topic:** {prefix}/{clientId}/commands/send-keys
**Payload:** `'<alt>+<ctrl>+<delete>'`
or
**Payload:** `'<CTRL>+<SHIFT>+o'`
or anything you might think of.
