### ISSUE TITLE
Almalinux install 

### ISSUE THREAD

**Issue by avocadio** [bkbilly/lnxlink#40]
For reference the installation on Almalinux works using the following:
`dnf install python39-pip.noarch gcc cmake dbus-devel glib2-devel python39-devel alsa-lib-devel`
(default pip3 on almalinux 8 does not work)

I suspect this also would work on Centos but can't test it. 

xdotool xprintidle are not expected to work on wayland.  xprintidle seems to replaced by dbus (https://unix.stackexchange.com/questions/396911/how-can-i-tell-if-a-user-is-idle-in-wayland/492328#492328).

I've used https://git.sr.ht/~geb/dotool/archive/1.1.tar.gz to replaced xdotool on another project but it is not in any RPM repo.

**Comment by bkbilly** [comment]
Thanks for the installation instructions.
There is an alternative for the `idle-time`, but I am going to need your help with that.
I've created a new python library and I would like for you to try it out.
There are instructions in the repository:
https://github.com/bkbilly/dbus_idle
