### ISSUE TITLE
Check Package Manager for system updates

### ISSUE THREAD

**Issue by bkbilly** [bkbilly/lnxlink#42]
**Describe the solution you'd like**
It would be ace if LNXLink could you show whether systems updates are available (yum/apt).

**Additional context**
No updates are available:
 - APT  (> 2): `apt list --upgradable | wc -l` 

If anyone knows the other package managers how to get the updates, let me know.

**Comment by Iceman248** [comment]
`yay`

That's all that has to be type to update EndeavourOS, based on Arch Linux to do a full system update.

**Comment by bkbilly** [comment]
Actually I need the commands that will show if there are updates or not which will be running every several seconds.
The result is a binary sensor that informs the user if there are updates or not.

**Comment by Iceman248** [comment]
`checkupdates`

That seems to be what you're looking for.

**Comment by Iceman248** [comment]
How about an option regarding how often it checks? Every several seconds sounds excessive. I wouldn't want it check too many times in one day.

**Comment by avocadio** [comment]
That's great news 
The yum/dnf version is:

yum -q updateinfo list updates | wc -l

**Comment by bkbilly** [comment]
Added this feature on the latest release `2023.3.1`.
