### ISSUE TITLE
usage area

### ISSUE THREAD

**Issue by jerome6994** [bkbilly/lnxlink#43]
Hello

I have a question of use does ln link work on Debian 10 or 11 machine? (example proxmox or proxmox virtual machine)

If yes I have a failure on the command `pip3 install -U lnxlink` and how to fix this?

![image](https://user-images.githubusercontent.com/66921143/220466921-780f643b-8ae3-4c19-8e13-3b22084604df.png)

**Comment by bkbilly** [comment]
You should be able to install on any linux distro, including Debian.
I haven't seen this error before, but you could try this:
```bash
sudo pip3 install -U pip
pip3 install -U lnxlink
```

If it doesn't work send me the result of this command
```bash
pip3 -V
```

You could also try installing another python package to check if it works:
```bash
pip3 install PyYAML
```

**Comment by jerome6994** [comment]
Good evening

So I just placed the two commands and I still have an error on the second command

![image](https://user-images.githubusercontent.com/66921143/220760843-2e601965-195d-491b-ad80-d0bb4a47bd4d.png)

For `pip3 -v`
`pip 23.0.1 from /usr/local/lib/python3.9/dist-packages/pip (python 3.9)
`

**Comment by bkbilly** [comment]
I haven't tried it on raspberry, but you could try this:
```
pip3 uninstall gi pgi
sudo pip3 uninstall gi pgi
sudo apt install python3-gi
```

When I get the chance, I will try it myself on a raspberry pi 4.

**Comment by bkbilly** [comment]
I've tried installing it a fresh installation of raspbian lite on a raspberry pi 4 and it works for me.
The only changes i've made are to disable these from the `config.yaml` file:
- camera_used
- idle
- nvidia_gpu
