### ISSUE TITLE
Client Id in sensor/switch name in home assistant

### ISSUE THREAD

**Issue by rick00001** [bkbilly/lnxlink#44]
Could the client id be includes in all the auto discovered device names in home assistant? 

I'am using your great app on multiple servers and i'am having troubels keeping the devices apart.
The naming is like:
- sensor.cpu_usage
- sensor.cpu_usage_2

It would be nice if it could be:
sensor.<<client id>>cpu_usage for instance

**Comment by bkbilly** [comment]
I haven't used it on more than 1 computers, so I never though about it.
Thanks for pointing it out. I'll add this on the next release

**Comment by jbstep** [comment]
That would be awesome. I have it on 5 computers in my classroom.

**Comment by bkbilly** [comment]
I've released the new version with the feature you requested.
