### ISSUE TITLE
Command not found

### ISSUE THREAD

**Issue by Xkim2000** [bkbilly/lnxlink#47]
I installed and everything went ok, but when I try to start the service says that the command is not found.

Command: 
systemctl --user start lnxlink
Output:
Failed to start lnxlink.service: Unit lnxlink.service not found.
Thanks in advance

**Comment by bkbilly** [comment]
You need to follow the installation instructions.
Most likely you skipped this command:
`lnxlink -c config.yaml`

**Comment by Xkim2000** [comment]
Is exactly in that command.
![image](https://user-images.githubusercontent.com/32307460/228237867-94c69c96-6e6f-44ec-94ed-e27280f9758a.png)

**Comment by bkbilly** [comment]
Send me the result of this command:
```
pip3 install -U lnxlink
```

**Comment by Xkim2000** [comment]
The pip3 command:
![image](https://user-images.githubusercontent.com/32307460/228357703-e0eebc86-4406-4ac7-b065-f75bba53045a.png)

**Comment by bkbilly** [comment]
Have you tried the command I wrote above?
```
~/.local/bin/lnxlink -c config.yaml
```

**Comment by Xkim2000** [comment]
It's working now. I had some problems with some paths.
![image](https://user-images.githubusercontent.com/32307460/229190428-f8f9b354-c32a-4095-a552-c8bf24635a9d.png)
Thanks for your support bro. Keep up the good work.

**Comment by bkbilly** [comment]
I am glad that it worked for you!
