### ISSUE TITLE
What to do with update notifications

### ISSUE THREAD

**Issue by bmcclure** [bkbilly/lnxlink#51]
I'm not sure if this is a bug or just a lack of understanding about how this is supposed to work.

I have a Home Assistant automation that sends notifications to my phone when any update is available. The notification lets me start the update, or I can also go to the Home Assistant UI and start the update from Settings like normal.

Every day I see notifications on my phone for new lnxlink versions available, but the update isn't listed in the HA user interface. It's like it disappears shortly after appearing, even though it was not actually updated.

I've tried hitting the Update button from the phone notification, but since the update entity no longer appears in HA, I'm guessing that's why it doesn't work.

So I guess my question is whether or not this is the expected behavior? If there is an updatere available, shouldn't the update entity stay in Home Assistant until it's dismissed or updated?

As a secondary question, should I actually be able to install the update to lnxlink from HA? That would be incredible, but thus far the only way I can get it to actually update is manually running `pip install --upgrade lnxlink` from the laptop I'm running it on.

Thanks so much for the assistance!

**Comment by bkbilly** [comment]
The update entity doesn't support updating through update.install service and that's why there is no update button on the entity. I will keep it in mind as a feature request to update it like this. 

The entities of lnxlink become unavailable once you turn off your laptop. You can find them all under the MQTT integration. 

I am not sure why you get notifications on your phone. If you want, you can send me the automation to check it out.

**Comment by bmcclure** [comment]
Thanks for the reply, that explains a couple of things! However it seems there may be some sort of bug with how the update entity for lnxlink works, at least in my case.

I know why I get the phone notifications, and I'm good with those--I mentioned them because they are the only way I actually know there's a lnxlink update available. Without those, I never would see any update entity in Home Assistant for lnxlink since they seem to disappear immediately. What I'm wondering is, why do they disappear from Home Assistant immediately even though my laptop is running 24/7 and there's still an update available?

With other update entities in Home Assistant that I see, the update stays there while it's still outdated. The available updates appear in a list in the Settings section, and they don't typically disappear immediately after they show up unless automatic updates are turned on.

**Comment by bkbilly** [comment]
I've also noticed that it doesn't appear on settings, and I believe that it's because it doesn't support installation though home assistant.

**Comment by bmcclure** [comment]
That must explain it! This is probably working as designed currently so I think this issue can be closed. Thanks for the clarification!
