### ISSUE TITLE
cant systemctl enable it

### ISSUE THREAD

**Issue by elchanly** [bkbilly/lnxlink#52]
Sorry to bother but im pulling my hairs out...  I cant figure out how to get this work.
I install with your sequence of commands and it works, but i cant make it work via systemd, i try via sudo systemctl enable lnxlink and throws this message
Failed to enable unit: Unit /run/systemd/generator.late/lnxlink.service is transient or generated.
When i start it via sudo lnxlink -c config.yaml
it says SystemD service not found or it's not running and starts to work, but as soon as i stop it... maybe its something related with systemd, but i can use systemctl with other services and they work (i dont know too much about this topic)

Im trying lots of things but nothing works, 
Can someone help me?
Thanks!

**Comment by elchanly** [comment]
Oh sorry I forgot.... 
My linux distro is Ubuntu 23.04 and i have this when i install and subsequently try to make it a system service:
(apparently systemd is not found, but i can systemctl enable things, and when i try to do it with lnxlink it says 
Failed to restart lnxlink.service: Unit lnxlink.service not found.)

i have to say i tried to install it in other systems and get the same error, but earlier versions (i can recall, maybe a year or more...) i could...


<<<<<<<<
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
    python3-xyz, where xyz is the package you are trying to
    install.
    
    If you wish to install a non-Debian-packaged Python package,
    create a virtual environment using python3 -m venv path/to/venv.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
    sure you have python3-full installed.
    
    If you wish to install a non-Debian packaged Python application,
    it may be easiest to use pipx install xyz, which will manage a
    virtual environment for you. Make sure you have pipx installed.
    
    See /usr/share/doc/python3.11/README.venv for more information.

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.
SystemD service not found or it's not running...
 Install as a user service? (True/False) [True]: 
Failed to connect to bus: No se ha encontrado el medio
Failed to connect to bus: No se ha encontrado el medio
LNXlink 2023.4.0 started: 3.11.2

**Comment by bkbilly** [comment]
I still can't understand what exactly is the issue you are facing, but here are some instructions to remove everything and install it again:

You will have to choose an installation process. I would suggest removing everything and starting from scratch:
```bash
sudo pip3 uninstall -U lnxlink
sudo pip3 uninstall -U lnxlink
pip3 install -U lnxlink
rm ~/.config/systemd/user/lnxlink.service
sudo rm /etc/systemd/system/lnxlink.service
```

and then follow the installation instructions: https://github.com/bkbilly/lnxlink#installation
Keep in mind that you will have to choose either the Headless installation if you are experienced linux user or the 1st which is for graphical.

**Comment by elchanly** [comment]
it worked using installation for desktop, not for headless. the only thing i see different (appart from packages) is that headless uses sudo and desktop doesnt, idk why using sudo makes a trouble for me. anyway, thanks and congrats for this so so useful app.

**Comment by bkbilly** [comment]
I am happy that it worked for you!
The reason behind the sudo, is that the super user doesn't have access to the user's display which many addons are depending on it. With some workarounds, it might work, but for now it only works as a user service.
