### ISSUE TITLE
Restart instead of shutdown

### ISSUE THREAD

**Issue by Tekno-man** [bkbilly/lnxlink#6]
I think restart might be quite a useful command. I have added it to my install (cant try it yet but will report back) this should be the command.

import subprocess

class Addon():
    service = 'restart'
    name = 'Restart'
    icon = 'mdi:power'
    unit = 'json'

    def startControl(self, topic, data):
        print(topic, data)
        subprocess.call(["shutdown", "-r", "-t", "30"])

**Comment by bkbilly** [comment]
I didn't think that it would be useful, but if you find it useful we can add it.
If you are already working on it you can make a pull request.

**Comment by Tekno-man** [comment]
Its good if there is some bug in your linux system that can be fixed by a restart. I have never done a pull request before I will look into how to do it. In the meantime though I tried it out and the command works for restarting the system. I wasn't quote sure how to add it to the autodiscovery part of HA though. There also seems to be some instability in the network when you add and remove some modules.

**Comment by boutch** [comment]
Agreed 100%, I am actually looking for a restart rather than a shutdown. I do have Rpi everywhere in the house and sometimes they need restarting.

**Comment by bkbilly** [comment]
Sorry for the long wait, but I finally added the extra module for the restart you asked me to.
Happy restarting. 😃
