### ISSUE TITLE
Can't load addon: disk_usage

### ISSUE THREAD

**Issue by ScottG489** [bkbilly/lnxlink#60]
### What type of installation are you running?

Desktop

### Which Linux OS are you using?

Ubuntu 22.04

### Which version of LNXLink has the issue?

2023.6.1

### Describe the problem

I run the program(`lnxlink -c ~/.lnxlinkrc`) and then the error below shows up every refresh.

I think the problem is that it's trying to access some docker resource which it doesn't have permission to, but I don't think it makes sense to try to use this as a disk. I saw this with another Linux companion app I tried. I might be a good idea just to filter out docker disks completely.

### Additional context

I also get this error, but it makes sense since I don't have an amd_gpu. However, it might be a good idea to detect this and just disable the module:
```
Can't load addon: amd_gpu
Traceback (most recent call last):
  File "/home/scott/.local/lib/python3.10/site-packages/lnxlink/__main__.py", line 77, in monitor_run
    pub_data = addon.getInfo()
  File "/home/scott/.local/lib/python3.10/site-packages/lnxlink/modules/amd_gpu.py", line 12, in getInfo
    first_gpu = pyamdgpuinfo.get_gpu(0)                        # we'll ignore extra GPUs
  File "pyamdgpuinfo/_pyamdgpuinfo.pyx", line 173, in pyamdgpuinfo._pyamdgpuinfo.get_gpu
  File "pyamdgpuinfo/_pyamdgpuinfo.pyx", line 228, in pyamdgpuinfo._pyamdgpuinfo.get_gpu
RuntimeError: GPU id 0 not found
```
Happy to file this as a separate issue if you'd like.

### Configuration

```yaml
mqtt:
  prefix: lnxlink
  clientId: DESKTOP-Linux
  statsPrefix: monitor/stats
  server: 10.0.0.223
  port: 1883
  auth:
    user: mosquitto_broker_user
    pass: wasd159731
  discovery:
    enabled: true
  lwt:
    enabled: true
    qos: 1
    retain: true
    connectMsg: 'ON'
    disconnectMsg: 'OFF'
update_interval: 5
modules: null
```

### Logs

FYI `journalctl --user -u lnxlink -n 300 --no-pager` gives no output, but here are just the logs from the terminal after running the application:

```
Can't load addon: disk_usage
Traceback (most recent call last):
  File "/home/scott/.local/lib/python3.10/site-packages/lnxlink/__main__.py", line 77, in monitor_run
    pub_data = addon.getInfo()
  File "/home/scott/.local/lib/python3.10/site-packages/lnxlink/modules/disk_usage.py", line 17, in getInfo
    disk_stats = psutil.disk_usage(disk.mountpoint)
  File "/home/scott/.local/lib/python3.10/site-packages/psutil/__init__.py", line 2000, in disk_usage
    return _psplatform.disk_usage(path)
  File "/home/scott/.local/lib/python3.10/site-packages/psutil/_psposix.py", line 175, in disk_usage
    st = os.statvfs(path)
PermissionError: [Errno 13] Permission denied: '/var/lib/docker/overlay2/14c88c96744bdbce6237ffb04b1cbf60b881de57a87f35734df543f110100c22/diff'
```

**Comment by bkbilly** [comment]
For the AMD GPU addon, I am planning on combining it with the NVIDIA GPU addon, but I didn't get the chance to do it yet.
Most likely on the next release I will fix this.

As for your disk problem, could you run this python script and send me the result?
```python
import psutil

for disk in psutil.disk_partitions():
    if disk.fstype == 'squashfs':
        continue
    print(disk.mountpoint, disk.fstype)
```

Keep in mind that you have the option to ignore the disk_usage module as described here: https://github.com/bkbilly/lnxlink/tree/master#one-of-my-integration-is-not-working

**Comment by ScottG489** [comment]
Here's the output:
```
/ ext4
/boot ext4
/var/lib/docker/overlay2/14c88c96744bdbce6237ffb04b1cbf60b881de57a87f35734df543f110100c22/diff ext4
```
After running a `docker system prune -a` that last entry goes away. I do a lot of development with docker so I can definitely see there being a large number of these at some point.

**Comment by ScottG489** [comment]
One other small question so I don't spam you with issues, but is it possible to run lnxlink as a service while also having access to functionality related to the display? (e.g. screenshot, idle, etc.)

I would really like to be able to run this as a service so it automatically starts with my computer.

**Comment by bkbilly** [comment]
Thanks for mentioning the DISPLAY on the service info. I haven't used it before, but I will try it out.

Could you run an alteration to the script above to check if the docker mount shows up again?
```python
import psutil

for disk in psutil.disk_partitions(all=False):
    if disk.fstype == 'squashfs':
        continue
    print(disk.mountpoint, disk.fstype)
```

**Comment by ScottG489** [comment]
Let me start up some containers so that I get the bad results with the first script and then I'll try this one.

**Comment by ScottG489** [comment]
Ok I was able to reproduce, but unfortunately that new script still shows the `/var/lib/docker` result. I can confirm it doesn't have to do with docker volume though because I just deleted them all and it's still showing up in the script output.

**Comment by bkbilly** [comment]
To exclude modules from the default configuration should be easy to implement, but I'll have to look into it. 
To add options to each module it will take some work, so no promises yet.
For now I have updated with the filter I mentioned earlier. You can only test it if you use the developer installation that I mention on the updated documentation.

**Comment by ScottG489** [comment]
To get familiar with doing some dev on this project I was attempting to create my own module. However, after adding it I was getting this error in the logs:
```
Jun 25 23:01:13 scott-desktop-linux systemd[2283]: Started LNXlink.
Jun 25 23:01:14 scott-desktop-linux lnxlink[531715]: Traceback (most recent call last):
Jun 25 23:01:14 scott-desktop-linux lnxlink[531715]:   File "/home/scott/.local/lib/python3.10/site-packages/lnxlink/modules/__init__.py", line 33, in parse_modules
Jun 25 23:01:14 scott-desktop-linux lnxlink[531715]:     addon = getattr(import_module(f"{module_name}"), 'Addon')
Jun 25 23:01:14 scott-desktop-linux lnxlink[531715]: AttributeError: module 'test' has no attribute 'Addon'
```
The file was named `~/test.py` and referenced as such in my lnxlink config.

**Comment by bkbilly** [comment]
It seems like the class `Addon` doesn't exist on your module.
If you attach it here, I could help you.

**Comment by ScottG489** [comment]
Well it's basically just the example in the docs. The docs make it seem like I can put it anywhere. Does the module file need to go in a specific place?

**Comment by bkbilly** [comment]
You can put it anywhere in your system, but it needs to have a specific format as explained on the docs.
You can see a simple example with the cpu found here: https://github.com/bkbilly/lnxlink/blob/master/lnxlink/modules/cpu.py

**Comment by ScottG489** [comment]
Thanks yeah, it was cuz it was named `test.py`. Of course it was something stupid haha. Might be worth mentioning in the docs?

**Comment by bkbilly** [comment]
You are right, I'll update the docs.

**Comment by ScottG489** [comment]
So I was getting started with development. I've cloned the repo and followed the dev setup documentation (`pip3 install -e .`, etc), but getting errors related to the `distro` import:

```
ModuleNotFoundError: No module named 'distro'
```
I added it to the `dependencies` list in `pyproject.toml` and this fixed the problem. I think maybe since I'm running it in a venv vs how this is run at a system level normally where the `distro` package would be available was causing the problem?

I'm a novice python dev so I'm just using general knowledge here, but if true we should probably be explicit about this dependency and add it.

Also, do you happen to have a discord for this project or some other way I could contact you to coordinate development? Don't want to keep spamming this issue :)
