### ISSUE TITLE
Error on updating lnklink using pip3

### ISSUE THREAD

**Issue by renarena** [bkbilly/lnxlink#65]
### What type of installation are you running?

Desktop

### Which Linux OS are you using?

Linux Mint Debian Edition

### Which version of LNXLink has the issue?

where can i look up? files from 2023-02-04

### The problem

i try to run  `pip3 install -U lnxlink` to update lnxlink and get
```
ERROR: Could not find a version that satisfies the requirement lnxlink (from versions: none)
ERROR: No matching distribution found for lnxlink

```

**Comment by bkbilly** [comment]
Try this command first:
```bash
sudo pip3 install -U pip
```

**Comment by renarena** [comment]
worked :-)

**Comment by renarena** [comment]
May be add it to documentation?
