### ISSUE TITLE
Trying to make work in headerless linux

### ISSUE THREAD

**Issue by Tekno-man** [bkbilly/lnxlink#7]
Hi just learned about this app, looks great, thanks for putting it together, will be so much better than using SSH. I installed it onto a proxmox host hoping to get some details into HA. The problem is that after entering in all the details im not seeing any attempts to connect on the MQTT broker. Is there any troubleshooting steps you could recommend or any logs i can see from the app?
EDIT:
looking at previous issues i found the below command and the output from it (if you would prefer issues in the github please me know)

root@proxmox:~# systemctl --user status lnxlink
● lnxlink.service - LNXLink
     Loaded: loaded (/root/.config/systemd/user/lnxlink.service; enabled; vendor preset: enabled)
     Active: active (running) since Mon 2022-01-31 15:29:55 AEDT; 13s ago
   Main PID: 96503 (python3)
      Tasks: 1 (limit: 38084)
     Memory: 16.9M
        CPU: 109ms
     CGroup: /user.slice/user-0.slice/user@0.service/app.slice/lnxlink.service
             └─96503 /usr/bin/python3 /opt/lnxlink/run.py

Jan 31 15:30:07 proxmox python3[96503]:     return _bootstrap._gcd_import(name[level:], package, level)
Jan 31 15:30:07 proxmox python3[96503]:   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
Jan 31 15:30:07 proxmox python3[96503]:   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
Jan 31 15:30:07 proxmox python3[96503]:   File "<frozen importlib._bootstrap>", line 986, in _find_and_load>
Jan 31 15:30:07 proxmox python3[96503]:   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
Jan 31 15:30:07 proxmox python3[96503]:   File "<frozen importlib._bootstrap_external>", line 790, in exec_>
Jan 31 15:30:07 proxmox python3[96503]:   File "<frozen importlib._bootstrap>", line 228, in _call_with_fra>
Jan 31 15:30:07 proxmox python3[96503]:   File "/opt/lnxlink/modules/media.py", line 1, in <module>
Jan 31 15:30:07 proxmox python3[96503]:     from dbus.mainloop.glib import DBusGMainLoop
Jan 31 15:30:07 proxmox python3[96503]: ModuleNotFoundError: No module named 'dbus'
...skipping...
also dbus is installed
root@proxmox:~# sudo apt-get install dbus
Reading package lists… Done
Building dependency tree… Done
Reading state information… Done
dbus is already the newest version (1.12.20-2).

root@proxmox:~# pip3 install pydbus
Requirement already satisfied: pydbus in /usr/local/lib/python3.9/dist-packages (0.6.0)

tried installing sudo apt install python3-dbus

but then i get this error

● lnxlink.service - LNXLink
     Loaded: loaded (/root/.config/systemd/user/lnxlink.service; enabled; vendor preset: enabled)
     Active: active (running) since Mon 2022-01-31 20:32:09 AEDT; 50s ago
   Main PID: 149058 (python3)
      Tasks: 1 (limit: 38084)
     Memory: 20.1M
        CPU: 136ms
     CGroup: /user.slice/user-0.slice/user@0.service/app.slice/lnxlink.service
             └─149058 /usr/bin/python3 /opt/lnxlink/run.py

Jan 31 20:33:00 proxmox python3[149058]:     from pynput import keyboard
Jan 31 20:33:00 proxmox python3[149058]:   File "/usr/local/lib/python3.9/dist-packages/pynput/__init__.py", line 40, in <module>
Jan 31 20:33:00 proxmox python3[149058]:     from . import keyboard
Jan 31 20:33:00 proxmox python3[149058]:   File "/usr/local/lib/python3.9/dist-packages/pynput/keyboard/__init__.py", line 31, in <module>
Jan 31 20:33:00 proxmox python3[149058]:     backend = backend(__name__)
Jan 31 20:33:00 proxmox python3[149058]:   File "/usr/local/lib/python3.9/dist-packages/pynput/_util/__init__.py", line 76, in backend
Jan 31 20:33:00 proxmox python3[149058]:     raise ImportError('this platform is not supported: {}'.format(
Jan 31 20:33:00 proxmox python3[149058]: ImportError: this platform is not supported: ('failed to acquire X connection: Bad display name ""', DisplayNameError(''))
Jan 31 20:33:00 proxmox python3[149058]: Try one of the following resolutions:
Jan 31 20:33:00 proxmox python3[149058]:  * Please make sure that you have an X serve

**Comment by Tekno-man** [comment]
As you suggested i have tried deleting these files:
send_keys.py
media.py
notify.py

and now get this error. Thanks again
● lnxlink.service - LNXLink
     Loaded: loaded (/root/.config/systemd/user/lnxlink.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Wed 2022-02-02 10:35:55 AEDT; 1s ago
    Process: 1690 ExecStart=/usr/bin/python3 /opt/lnxlink/run.py (code=exited, status=1/FAILURE)
   Main PID: 1690 (code=exited, status=1/FAILURE)
        CPU: 144ms

Feb 02 10:35:55 proxmox systemd[1664]: lnxlink.service: Scheduled restart job, restart counter is at 5.
Feb 02 10:35:55 proxmox systemd[1664]: Stopped LNXLink.
Feb 02 10:35:55 proxmox systemd[1664]: lnxlink.service: Start request repeated too quickly.
Feb 02 10:35:55 proxmox systemd[1664]: lnxlink.service: Failed with result 'exit-code'.
Feb 02 10:35:55 proxmox systemd[1664]: Failed to start LNXLink.

**Comment by bulburDE** [comment]
It worked for me after I deleted the files you mentioned and removed the entries from /opt/lnxlink/config.yaml

**Comment by Tekno-man** [comment]
thanks for the tip I just removed them from the config.yaml in the control and monitoring but still get the same error. I restarted the service after saving changes. the only other thing different i have done is that i had to install python3-dbus

**Comment by Tekno-man** [comment]
after trying a few time the error only occurs after i delete the send_keys.py, deleting the other 2 files is fine. The error also doesnt occur if i just rename the send_keys.py.

**Comment by bulburDE** [comment]
IMHO deleting or renaming should have the same effect. Maybe it was just a coincidence. I have some errors with the `network` module. I get errors like `KeyError: 'network'` or `AttributeError: 'LNXlink' object has no attribute 'Addons'` when starting lnxlink. Different behaviour each time I start it even though I didn't change anything. Must be some race condition, maybe something mqtt related.

**Comment by Tekno-man** [comment]
it works now running it manually like this 
systemctl --user stop lnxlink.service
cd /opt/lnxlink
/usr/bin/python3 /opt/lnxlink/run.py

**Comment by Tekno-man** [comment]
found that when i tried to change this value it would throw a network error 
statsPrefix: windows-monitor/stats

**Comment by bkbilly** [comment]
Seems that the issue has been resolved, so I am closing it.
