### ISSUE TITLE
Power profile

### ISSUE THREAD

**Issue by answer35** [bkbilly/lnxlink#71]
### Describe the solution you'd like

Hello, great work, I was also using IoT Link on windows and when I decided to switch to Linux, I was looking everywhere for a similar solution. Thanks to you it was easy to find it ;)
Do you think it could be possible to get power profile information and command so we could make automation to switch between performance mode to battery saving when screen is locked for example ? and switch it back to performance when unlocked.

**Comment by bkbilly** [comment]
This could be possible with the [powerprofilesctl](https://sleeplessbeastie.eu/2022/09/12/how-to-control-power-profiles-daemon-using-command-line/).
I'll look into it once I get the chance.

**Comment by bkbilly** [comment]
I've added this feature on the development version of LNXlink, but I haven't tested it.
Let me know if you have any issues.

**Comment by answer35** [comment]
I made the upgrade with command line `pip3 install -U lnxlink`
But I don't see anything related to power profile showing up in MQTT yet

**Comment by bkbilly** [comment]
You will have to uninstall and install using the [development](https://bkbilly.gitbook.io/lnxlink/setup) version, or wait for the next release of LNXlink.

**Comment by answer35** [comment]
Okay i reinstall with development version and power profile works great, selection is applied very quickly. It will be really interesting to make automation with this :) thank you for the great work ;)
When will be the stable version including that ? To know when I will be able to go back on stable release instead ?

**Comment by bkbilly** [comment]
I've made a lot of changes this month which I haven't tested myself. 
If everything works as expected, I'll release the 2023.9.0 version in about a week.

**Comment by answer35** [comment]
Okay I will follow the future release then. Thank you
