### ISSUE TITLE
can't compile on arm architecture

### ISSUE THREAD

**Issue by fireport** [bkbilly/lnxlink#74]
### What type of installation are you running?

Server

### Which Linux OS are you using?

debian 11.7

### Which version of LNXLink has the issue?

latest

### The problem

Installation on arm64 fail with this error:
`      pyamdgpuinfo/_pyamdgpuinfo.c:1195:10: fatal error: xf86drm.h: File o direc                                                                          tory non esistente
       1195 | #include "xf86drm.h"
            |          ^~~~~~~~~~~
      compilation terminated.
      error: command '/usr/bin/aarch64-linux-gnu-gcc' failed with exit code 1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem wit                                                                          h pip.
  ERROR: Failed building wheel for pyamdgpuinfo
Failed to build pyamdgpuinfo
ERROR: Could not build wheels for pyamdgpuinfo, which is required to install pyp                                                                          roject.toml-based projects
`
will be possible to exclude this module from dependencies ?
Thank you

**Comment by bkbilly** [comment]
I'll have to rethink how the dependencies are installed, but for now you could install LNXlink using the development method and remove line on `pyproject.toml` that uses the dependency `pyamdgpuinfo`.

**Comment by bkbilly** [comment]
I've pushed an update on dev installation that imports the libraries automatically, so if you exclude the GPU on your config, it should not try to install it.

**Comment by fireport** [comment]
Yes ! It works.
Thank you
