### ISSUE TITLE
Support for newer Debian-based distributions and their hardcore take on external package managers

### ISSUE THREAD

**Issue by riddley** [bkbilly/lnxlink#75]
### Describe the solution you'd like

Thank you very much for writing this integration. I'm very excited to use it. I'm primarily a Debian user and as of version 12 they (along with newer Ubuntu and likely other Debian-based distros) issue this warning when you try to use pip:

    pip install -U pip
    error: externally-managed-environment

    × This environment is externally managed
    ╰─> To install Python packages system-wide, try apt install
        python3-xyz, where xyz is the package you are trying to
        install.

        If you wish to install a non-Debian-packaged Python package,
        create a virtual environment using python3 -m venv path/to/venv.
        Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
        sure you have python3-full installed.

        If you wish to install a non-Debian packaged Python application,
        it may be easiest to use pipx install xyz, which will manage a
        virtual environment for you. Make sure you have pipx installed.

        See /usr/share/doc/python3.11/README.venv for more information.

    note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
    hint: See PEP 668 for the detailed specification.

---

It would be great if there was either venv instructions or a .deb package or something. I'm not super well versed in Python and its environment-hacks so I don't feel super comfortable venturing into venv just for one application. Thanks!

**Comment by bkbilly** [comment]
I don't think there is a need to install LNXlink as a virtual environment. It will only make installation more complicated.
As for your error message you could use this command to install PIP:
```bash
sudo pip install --break-system-packages -U pip
```

This won't create any issue with your system, it will just get the latest PIP version.
The rest of the commands should work without any issue.

**Comment by Georift** [comment]
Not sure if I've set myself up for failure but I just encountered this and went the other route:

```
sudo apt install pipx
pipx install lnxlink
```

Lets see how it goes.

**Comment by Georift** [comment]
> Lets see how it goes.

Was running into a few issues, (trouble getting the `DISPLAY=:0`, so backed out and went with the `--break-system-packages` route listed above.

However I encountered the same issues with the global pip install.

I would be hesitant to deviate too much from Debian's warnings here. Things like this can get funky quickly. I may jump back to the `pipx` method shortly. I'll report back if I do and things work ok.

**Comment by bkbilly** [comment]
In order to install LNXlink as a virtual environment you will have to follow these instructions:
```bash
sudo pip install virtualenv  # This has to be installed globally
python3 -m venv /home/user/lnxlink_venv
source /home/user/lnxlink_venv/bin/activate
pip install -e .
```
Edit the file `/home/user/.config/systemd/user/lnxlink.service` and do this change:
```
# Replace this line
ExecStart=/home/user/.local/bin/lnxlink -c /home/user/lnxlink/config.yaml`
# With this line
ExecStart=/home/user/lnxlink_venv/bin/lnxlink -c /home/user/lnxlink/config.yaml
```
Then you'll have to reload the service:
```bash
systemctl --user daemon-reload
systemctl --user restart lnxlink.service
```

**Comment by bkbilly** [comment]
I've added these instructions on the documentation, so this issue should be resolved.

**Comment by jeremysherriff** [comment]
For others that land here in the future after searching the issues for `venv` or `virtualenv`, the following is what finally worked for me:
```
sudo apt install pipx
pipx install lnxlink
```

I couldn't find the mentioned instructions in the documentation.

The situation I was recovering from was broken links in ~/.local/ which pointed to old python versions, broken during a release upgrade from 22.04.x to 24.04.x. HTH.
