### ISSUE TITLE
Can't connect to display ":0"

### ISSUE THREAD

**Issue by Georift** [bkbilly/lnxlink#76]
### What type of installation are you running?

Desktop

### Which Linux OS are you using?

Debian trixie/sid

### Which version of LNXLink has the issue?

lnxlink==2023.10.0

### Describe the problem

Cheers for the project, really useful to me so far :grin: 

My logs are showing some issues when connecting to display, but I think I've configured it correctly.

### Additional context

Pretty sure `DISPLAY` is configured correctly:

```
➜  ~ systemctl --user show-environment | grep DISPLAY
DISPLAY=:1
```

### Logs

```bash
Oct 15 16:34:22 laptop lnxlink[72659]: ERROR:lnxlink:Error with addon fullscreen: Can't connect to display ":0": [Errno 111] Connection refused
```

**Comment by bkbilly** [comment]
I've hardcoded the display as ":0". I didn't think that there would be another number for a display.
I'll fix it, but could you help me understand why you have a display with number 1 instead of 0?

**Comment by bkbilly** [comment]
I've pushed an update that should fix this, but you'll have to follow the developer installation of LNXlink.

**Comment by HoroTW** [comment]
I have a custom arch install with an nvidia card, I also run the desktop on `:1`.
Can confirm with the current code (dev install) it works! :slightly_smiling_face:

Also tested that the current pip build does not work and throws the "expected" error `ERROR:lnxlink:Error with addon fullscreen: Can't connect to display ":0": [Errno 111] Connection refused' (just to make sure I was really affected and could give a valid confirmation for the fix).

**Comment by bkbilly** [comment]
It's nice to hear that it works for the dev installation type. You'll be able to install it normally when I publish the next release.

**Comment by bkbilly** [comment]
I've added lot's of new features on the latest release: https://github.com/bkbilly/lnxlink/releases/tag/2023.11.0
