### ISSUE TITLE
Entities unavailable when restarting home assistant

### ISSUE THREAD

**Issue by gosoares** [bkbilly/lnxlink#8]
Firstly, thanks for the app, it's very helpful.

I was having a problem that when i restart home assistant all the entities from the app became unavailable, until i restart the pc, or at least the service.
I know very little about mqtt, but after doing some research, i actually already found a solution: set `retain = True` to the home assistant auto discovery messages.
But normally the entities should work after restarts even without retaining the messages? And is there some reason to the messages not being retained by default?

I'm running home assistant and mosquitto as docker containers, in case this is relevant.

**Comment by bkbilly** [comment]
You are absolutely right, the entities are not retained, so they become unavailable.
I will push a quick fix for that so that you can choose it if you want from the retain option in the yaml file.

**Comment by bkbilly** [comment]
I just pushed the fix.
Let me know if it works.
