### ISSUE TITLE
Unable to update from 2023.12.0 to 2023.12.1

### ISSUE THREAD

**Issue by appleimperio** [bkbilly/lnxlink#83]
### What type of installation are you running?

Other

### Which Linux OS are you using?

ebian GNU/Linux 12 (bookworm)

### Which version of LNXLink has the issue?

2023.12.0

### Description

I see a notification that i have an lnxlink update in the home assistant settings but when i hit update nothing happens.

**Comment by bkbilly** [comment]
You'll have to send me the logs so that I can figure out what happened.
These are located at the same directory as your config under the file name `lnxlink.log`

**Comment by appleimperio** [comment]
[lnxlink.log](https://github.com/bkbilly/lnxlink/files/13640802/lnxlink.log)

**Comment by ScottG489** [comment]
My updated failed as well and I found this error:

`Command 'pip install -U lnxlink' timed out after 3 seconds`

I ran the command myself and it succeeded and the update entity correctly refreshed after a restart of the service.

[Looking at the code it does in fact seem like there's a 3 second timeout.
](https://github.com/bkbilly/lnxlink/blob/master/lnxlink/modules/scripts/helpers.py#L9) For something like an update I think it should much higher (maybe even a minute or two?) just to be safe.

**Comment by bkbilly** [comment]
Thanks for letting me know about this. 
I've made this change after you reported the issue but I had to make sure this was the case based on your logs. 
I'll publish a new version and it will start working from that version onwards.

**Comment by appleimperio** [comment]
@bkbilly I install the xprintidle and exclude the power_profile. Can you explain me how to install the clvc I already install the VLC and the TTS is working. I try to update manually since I'm in a VENV what i do is
```
source lnxlink_venv/bin/activate
pip install lnxlink

systemctl --user restart lnxlink.service

```
I even restart Home Assistant but this message still there. Thanks fo your help

![Screenshot from 2023-12-11 19-43-52](https://github.com/bkbilly/lnxlink/assets/72883739/4647742a-8840-4420-9e05-9e5f377bda6d)

**Comment by bkbilly** [comment]
For updating it when installed as a virtual environment, you'll have to first activate the venv and then ulgrade/restart:
```
source lnxlink_venv/bin/activate
```

For the error you get, you will have to exclude the `keep_alive` module.

**Comment by appleimperio** [comment]
No luck yet. This is what i got when i try to reinstall it.
````
(lnxlink_venv) sdavila@raices:~/LNXlink$ pip install lnxlink
Requirement already satisfied: lnxlink in ./lnxlink_venv/lib/python3.11/site-packages (2023.12.0)
Requirement already satisfied: distro>=1.7.0 in ./lnxlink_venv/lib/python3.11/site-packages (from lnxlink) (1.8.0)
Requirement already satisfied: PyYAML>=5.3.1 in ./lnxlink_venv/lib/python3.11/site-packages (from lnxlink) (6.0.1)
Requirement already satisfied: paho-mqtt>=1.5.1 in ./lnxlink_venv/lib/python3.11/site-packages (from lnxlink) (1.6.1)
Requirement already satisfied: dbus-python>=1.3.2 in ./lnxlink_venv/lib/python3.11/site-packages (from lnxlink) (1.3.2)
Requirement already satisfied: requests>=2.28.1 in ./lnxlink_venv/lib/python3.11/site-packages (from lnxlink) (2.31.0)
Requirement already satisfied: pyOpenSSL>=22.1.0 in ./lnxlink_venv/lib/python3.11/site-packages (from lnxlink) (23.3.0)
Requirement already satisfied: jc>=1.23.0 in ./lnxlink_venv/lib/python3.11/site-packages (from lnxlink) (1.23.6)
Requirement already satisfied: pgi>=0.0.11.2 in ./lnxlink_venv/lib/python3.11/site-packages (from lnxlink) (0.0.11.2)
Requirement already satisfied: psutil>=5.8.0 in ./lnxlink_venv/lib/python3.11/site-packages (from lnxlink) (5.9.6)
Requirement already satisfied: notify2>=0.3.1 in ./lnxlink_venv/lib/python3.11/site-packages (from lnxlink) (0.3.1)
Requirement already satisfied: mpris2>=1.0.2 in ./lnxlink_venv/lib/python3.11/site-packages (from lnxlink) (1.0.2)
Requirement already satisfied: dbus-idle>=2023.3.2 in ./lnxlink_venv/lib/python3.11/site-packages (from lnxlink) (2023.3.2)
Requirement already satisfied: ewmh>=0.1.6 in ./lnxlink_venv/lib/python3.11/site-packages (from lnxlink) (0.1.6)
Requirement already satisfied: python-xlib in ./lnxlink_venv/lib/python3.11/site-packages (from ewmh>=0.1.6->lnxlink) (0.33)
Requirement already satisfied: ruamel.yaml>=0.15.0 in ./lnxlink_venv/lib/python3.11/site-packages (from jc>=1.23.0->lnxlink) (0.18.5)
Requirement already satisfied: xmltodict>=0.12.0 in ./lnxlink_venv/lib/python3.11/site-packages (from jc>=1.23.0->lnxlink) (0.13.0)
Requirement already satisfied: Pygments>=2.3.0 in ./lnxlink_venv/lib/python3.11/site-packages (from jc>=1.23.0->lnxlink) (2.17.2)
Requirement already satisfied: cryptography<42,>=41.0.5 in ./lnxlink_venv/lib/python3.11/site-packages (from pyOpenSSL>=22.1.0->lnxlink) (41.0.7)
Requirement already satisfied: charset-normalizer<4,>=2 in ./lnxlink_venv/lib/python3.11/site-packages (from requests>=2.28.1->lnxlink) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in ./lnxlink_venv/lib/python3.11/site-packages (from requests>=2.28.1->lnxlink) (3.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in ./lnxlink_venv/lib/python3.11/site-packages (from requests>=2.28.1->lnxlink) (2.1.0)
Requirement already satisfied: certifi>=2017.4.17 in ./lnxlink_venv/lib/python3.11/site-packages (from requests>=2.28.1->lnxlink) (2023.11.17)
Requirement already satisfied: cffi>=1.12 in ./lnxlink_venv/lib/python3.11/site-packages (from cryptography<42,>=41.0.5->pyOpenSSL>=22.1.0->lnxlink) (1.16.0)
Requirement already satisfied: ruamel.yaml.clib>=0.2.7 in ./lnxlink_venv/lib/python3.11/site-packages (from ruamel.yaml>=0.15.0->jc>=1.23.0->lnxlink) (0.2.8)
Requirement already satisfied: six>=1.10.0 in ./lnxlink_venv/lib/python3.11/site-packages (from python-xlib->ewmh>=0.1.6->lnxlink) (1.16.0)
Requirement already satisfied: pycparser in ./lnxlink_venv/lib/python3.11/site-packages (from cffi>=1.12->cryptography<42,>=41.0.5->pyOpenSSL>=22.1.0->lnxlink) (2.21)
(lnxlink_venv) sdavila@raices:~/LNXlink$
````

**Comment by bkbilly** [comment]
The command you used is for installing it, but for updating you will have to use the `-U` argument.
```
pip install -U lnxlink
```

**Comment by bkbilly** [comment]
I've released the 2023.12.2 version which includes the fix of updating. After this release you will be able to update LNXlink normally from home assistant.

**Comment by appleimperio** [comment]
I completely uninstalled and when I try to install the new version is not even starting up. I fix the other computer using the same method but with the old version and it's working. This is what I'm getting with the new version
```
(lnxlink_venv) lrivera@mastermind:~/lnxlink$ lnxlink -c config.yaml
Traceback (most recent call last):
  File "/home/lrivera/lnxlink/lnxlink_venv/bin/lnxlink", line 5, in <module>
    from lnxlink.__main__ import main
  File "/home/lrivera/lnxlink/lnxlink_venv/lib/python3.11/site-packages/lnxlink/__main__.py", line 22, in <module>
    from .system_monitor import MonitorSuspend, GracefulKiller
  File "/home/lrivera/lnxlink/lnxlink_venv/lib/python3.11/site-packages/lnxlink/system_monitor.py", line 9, in <module>
    from gi.repository import GLib
ModuleNotFoundError: No module named 'gi'
```

**Comment by bkbilly** [comment]
Could you try installing a python package and try running it again?
```
source lnxlink_venv/bin/activate
pip install pgi
```

**Comment by appleimperio** [comment]
same error

**Comment by bkbilly** [comment]
This should be able to fix your issue:
```
sudo apt install libgirepository1.0-dev
```

**Comment by appleimperio** [comment]
libgirepository1.0-dev is already the newest version (1.74.0-3)

**Comment by bkbilly** [comment]
Try installing all the libraries that are required:
```
sudo apt install patchelf meson libdbus-glib-1-dev libglib2.0-dev libasound2-dev libgirepository1.0-dev python3-pip xdotool xdg-utils python3-pyaudio
```

**Comment by appleimperio** [comment]
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

**Comment by bkbilly** [comment]
Seems that the 2023.12.2 release is broken. I'll have to find what's wrong and get back to you.

For now you can install 2023.12.1 like so:
```
pip install lnxlink==2023.12.1
```

**Comment by appleimperio** [comment]
Thank you

**Comment by bkbilly** [comment]
I think I found out how to run the 2023.12.2 version.
You can try installing these packages:
```
sudo apt install libcairo2-dev python3-gi
pip install pycairo PyGObject
```

**Comment by appleimperio** [comment]
This is the way! up and running. Should I wait until you fix the dependencies to update the other machine or is safe doing it this way?

**Comment by bkbilly** [comment]
Awesome! I am happy that it finally worked!
You can use it safely like this.

I'll update the documentation with these changes.
