### ISSUE TITLE
ModuleNotFoundError: No module named 'gi'

### ISSUE THREAD

**Issue by pipacsba** [bkbilly/lnxlink#84]
### What type of installation are you running?

Desktop

### Which Linux OS are you using?

Ubuntu 22.04, Python 3.10.12

### Which version of LNXLink has the issue?

2023.12.2

### Describe the problem

After updating to 2023.12.2 lnxlink is stopped, and syslog shows the error:
_Dec 12 20:20:32 -HP-EliteBook-8470p lnxlink[8737]:   File "/home/kaka/lnxlink_venv/lib/python3.10/site-packages/lnxlink/system_monitor.py", line 9, in <module>
Dec 12 20:20:32 -HP-EliteBook-8470p lnxlink[8737]:     from gi.repository import GLib
Dec 12 20:20:32 -HP-EliteBook-8470p lnxlink[8737]: ModuleNotFoundError: No module named 'gi'
Dec 12 20:20:32 -HP-EliteBook-8470p systemd[3280]: lnxlink.service: Main process exited, code=exited, status=1/FAILURE
Dec 12 20:20:32 -HP-EliteBook-8470p systemd[3280]: lnxlink.service: Failed with result 'exit-code'.
Dec 12 20:20:46 -HP-EliteBook-8470p systemd[3280]: Stopped LNXlink._

Following actions were needed on my side:
_sudo apt install libgirepository1.0-dev
pip install pycairo PyGObject_

**Comment by bkbilly** [comment]
Thanks for letting me know!
I'll try fixing it on the next release.

**Comment by bkbilly** [comment]
I've updated the documentation with your fix.
