### ISSUE TITLE
Install lnxlink onto a steamdeck

### ISSUE THREAD

**Issue by blackerking** [bkbilly/lnxlink#89]
### What type of installation are you running?

Desktop

### Which Linux OS are you using?

 SteamOS 3 (Arch-based)

### Which version of LNXLink has the issue?

current

### The problem

Hello there,

pip is not installed on a normal steamOS.
As package-manager is pacman installed and everything else are flatpakages.

Any Idea how I can install lnxlink?
I think the best solution would be without rooting the device.

I am ready to try it out some possibilitys.

Best regards.

**Comment by bkbilly** [comment]
I don't have SteamOS to try out, but if you have python installed, you could install pip like so:
```
wget https://bootstrap.pypa.io/get-pip.py  
python3 get-pip.py --user
```

**Comment by blackerking** [comment]
error: externally-managed-environment
-> pacman -S python-pup -> needs root access
Any suggestions?

**Comment by bkbilly** [comment]
Which command shows you this error?

**Comment by blackerking** [comment]
I am a step further:
Install PIP if necessary:
`python -m ensurepip` -> does the trick with pip

**Comment by blackerking** [comment]
`~/.local/bin/pip3 install -U lnxlink`
pkg-config not found -> Failed building wheel for pycairo

**Comment by bkbilly** [comment]
You are going to need to install some system dependencies which need root access.
The basic libraries needed are these:
```
patchelf meson libcairo2-dev libgirepository1.0-dev libdbus-glib-1-dev libglib2.0-dev
```

I am not sure if there is a way to install it without a root access...

**Comment by bkbilly** [comment]
I've made some changes that make the DBUS requirement optional, so you can install LNXlink it without needing the above libraries without a root access.

By not using the DBUS library you won't be able to use the media module and when you turn off your console it might not send the request for making the home assistant entities unavailable.

To try it, you'll have to uninstall and install it as a developer.

**Comment by blackerking** [comment]
Hey, I am still trying. I've contacted the makers of steam decky.
Maybe it is easier to maintain a decky plugin as instead a desktop application.

https://github.com/SteamDeckHomebrew/decky-loader

I will inform you when I got time to do more.

**Comment by bkbilly** [comment]
I am not familiar with the decky, but I've looked into the installation process and it seems that it requires root access by creating a temporary password like so:
```bash
# Creates a password "Decky!"
passwd deck
# Runs the installation commands
sudo .......
# Removes the password
sudo -S -k passwd -d dec
```

I would recommend following the same steps to create a temporary password and then install python and pip.
After that you can install LNXlink without root access.

**Comment by blackerking** [comment]
Hey I would like to make a last comment about all this.
I really thank you for your help, but the steamOS seems to much hardend against changes.
In other words I would have had changed many thinks to add a mqtt function inside my steam deck.

Thank you for your time

**Comment by bkbilly** [comment]
You will have to add the IP of the MQTT broker which is not installed on SteamDeck, so localhost and 127.0.0.1 won't work.
If you've installed it on your home assistant device, then you should put the IP of your Home Assistant.

**Comment by thpschris** [comment]
Thanks for the info! I got it working by installing mosquitto, allowing the connection on 0.0.0.0 and setting the Lnxlink address to 127.0.0.1.
@blackerking let me know if you need some help installing on your deck, I can write out the steps if needed.

**Comment by blackerking** [comment]
@thpschris Hey Thank you for your work. What are the installation steps? Did you unlock the filesystem?
