### ISSUE TITLE
AttributeError: 'Client' object has no attribute '_sock' and TypeError: Client.__init__() missing 1 required positional argument: 'callback_api_version'

### ISSUE THREAD

**Issue by emarvegt** [bkbilly/lnxlink#93]
### What type of installation are you running?

Desktop

### Which Linux OS are you using?

Debian 12

### Which version of LNXLink has the issue?

2024.2.1

### Describe the problem

I'm getting two errors when running the config wizard on Debian 12 (installed with pipx):

screen@screen:/opt/lnxlink$ lnxlink -c config.yaml
INFO:lnxlink:Config file not found.
INFO:lnxlink:Created new template: /opt/lnxlink/config.yaml
INFO:lnxlink:
Leave empty for default
 Enable MQTT automatic discovery (True/False) [True]: True
 MQTT server [192.168.1.1]: ........
 MQTT port [1883]: ....
 Enable TLS (True/False) [False]: false
 MQTT username [user]: .........
 MQTT password [pass]: .........
 Change clientId [DESKTOP-Linux]: screen
INFO:lnxlink:
All changes have been saved.
INFO:lnxlink: MQTT Topic prefix for for monitoring: lnxlink/screen/...
INFO:lnxlink: MQTT Topic prefix for for commands: lnxlink/screen/commands/...
INFO:lnxlink:SystemD service not found or it's not running...
 Install as a user service? (True/False) [True]: True
Created symlink /home/screen/.config/systemd/user/default.target.wants/lnxlink.service → /home/screen/.config/systemd/user/lnxlink.service.
INFO:lnxlink:LNXlink 2024.2.1, Python 3.11.2
INFO:lnxlink:Loaded addons: required_restart, sys_updates, cpu, microphone_used, display_env, update, shutdown, temperature, wifi, disk_usage, restart, camera_used, suspend, memory
Exception ignored in: <function Client.__del__ at 0x7f0070354ea0>
Traceback (most recent call last):
  File "/home/screen/.local/pipx/venvs/lnxlink/lib/python3.11/site-packages/paho/mqtt/client.py", line 874, in __del__
    self._reset_sockets()
  File "/home/screen/.local/pipx/venvs/lnxlink/lib/python3.11/site-packages/paho/mqtt/client.py", line 1133, in _reset_sockets
    self._sock_close()
  File "/home/screen/.local/pipx/venvs/lnxlink/lib/python3.11/site-packages/paho/mqtt/client.py", line 1119, in _sock_close
    if not self._sock:
           ^^^^^^^^^^
AttributeError: 'Client' object has no attribute '_sock'
Traceback (most recent call last):
  File "/home/screen/.local/bin/lnxlink", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/screen/.local/pipx/venvs/lnxlink/lib/python3.11/site-packages/lnxlink/__main__.py", line 513, in main
    lnxlink = LNXlink(config_file, args.exclude)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/screen/.local/pipx/venvs/lnxlink/lib/python3.11/site-packages/lnxlink/__main__.py", line 77, in __init__
    self.client = mqtt.Client()
                  ^^^^^^^^^^^^^
TypeError: Client.__init__() missing 1 required positional argument: 'callback_api_version'

### Logs

```bash
No entries here.
```

**Comment by bkbilly** [comment]
Since yesterday, the dependency for the MQTT connection `paho-mqtt` upgraded to version 2.0.0 that had some breaking changes.
There are two ways to fixing this issue:
1. Uninstall LNXlink and install it as a DEV user that includes the fix for this change.
2. Downgrade the paho-mqtt dependency to the supported version like so:
```bash
source /home/screen/.local/pipx/venvs/lnxlink/bin/activate
pip install -U paho-mqtt==1.6.1
```

The next version of LNXlink will include this fix.

**Comment by emarvegt** [comment]
Thanks for the quick reply. 
I attempted the second option and was able to downgrade paho-mqtt by adding --break-system-packages. 
However, then running lnxlink -c config.yaml still triggered the same errors, even after restarting the service and even re-installing lnxlink using pipx. The re-installation showed that indeed it was using paho-mqtt 1.6.1.

**Comment by bkbilly** [comment]
It seems that the command I told you doesn't work...
I found the correct one that installs the paho-mqtt on the virtual environment:
```bash
/home/screen/.local/pipx/venvs/lnxlink/bin/python -m pip install -U paho-mqtt==1.6.1
```

**Comment by bkbilly** [comment]
I've updated LNXlink to version `2024.2.2` which fixes your issue.
You can update using this command:
```bash
pipx upgrade lnxlink
```

**Comment by emarvegt** [comment]
Thanks for the quick replies!

I still cannot get this to work, now with an MQTT timeout. See below. Is that a problem with my mqtt auth or server/broker or an unexpected exception in LNXlink?

screen@screen:/opt/lnxlink$ /home/screen/.local/pipx/venvs/lnxlink/bin/python -m pip install -U paho-mqtt==1.6.1
Collecting paho-mqtt==1.6.1
  Using cached paho_mqtt-1.6.1-py3-none-any.whl
Installing collected packages: paho-mqtt
  Attempting uninstall: paho-mqtt
    Found existing installation: paho-mqtt 2.0.0
    Uninstalling paho-mqtt-2.0.0:
      Successfully uninstalled paho-mqtt-2.0.0
Successfully installed paho-mqtt-1.6.1
screen@screen:/opt/lnxlink$ pipx upgrade lnxlink
lnxlink is already at latest version 2024.2.2 (location:
/home/screen/.local/pipx/venvs/lnxlink)
screen@screen:/opt/lnxlink$ /home/screen/.local/pipx/venvs/lnxlink/bin/python -m pip install -U paho-mqtt==1.6.1
Requirement already satisfied: paho-mqtt==1.6.1 in /home/screen/.local/pipx/venvs/lnxlink/lib/python3.11/site-packages (1.6.1)
screen@screen:/opt/lnxlink$ lnxlink -c config.yaml
INFO:lnxlink:LNXlink 2024.2.2, Python 3.11.2
INFO:lnxlink:Loaded addons: required_restart, sys_updates, cpu, microphone_used, display_env, update, shutdown, temperature, wifi, disk_usage, restart, camera_used, suspend, memory
ERROR:lnxlink:Error establishing connection to MQTT broker: timed out, Traceback (most recent call last):
  File "/home/screen/.local/pipx/venvs/lnxlink/lib/python3.11/site-packages/lnxlink/__main__.py", line 196, in setup_mqtt
    self.client.connect(
  File "/home/screen/.local/pipx/venvs/lnxlink/lib/python3.11/site-packages/paho/mqtt/client.py", line 914, in connect
    return self.reconnect()
           ^^^^^^^^^^^^^^^^
  File "/home/screen/.local/pipx/venvs/lnxlink/lib/python3.11/site-packages/paho/mqtt/client.py", line 1044, in reconnect
    sock = self._create_socket_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/screen/.local/pipx/venvs/lnxlink/lib/python3.11/site-packages/paho/mqtt/client.py", line 3685, in _create_socket_connection
    return socket.create_connection(addr, timeout=self._connect_timeout, source_address=source)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/socket.py", line 851, in create_connection
    raise exceptions[0]
  File "/usr/lib/python3.11/socket.py", line 836, in create_connection
    sock.connect(sa)
TimeoutError: timed out

screen@screen:/opt/lnxlink$ pipx uninstall lnxlink
uninstalled lnxlink! ✨ 🌟 ✨
screen@screen:/opt/lnxlink$ pipx install lnxlink
  installed package lnxlink 2024.2.2, installed using Python 3.11.2
  These apps are now globally available
    - lnxlink
done! ✨ 🌟 ✨
screen@screen:/opt/lnxlink$ lnxlink -c config.yaml
INFO:lnxlink:LNXlink 2024.2.2, Python 3.11.2
INFO:lnxlink:Loaded addons: required_restart, sys_updates, cpu, microphone_used, display_env, update, shutdown, temperature, wifi, disk_usage, restart, camera_used, suspend, memory
ERROR:lnxlink:Error establishing connection to MQTT broker: timed out, Traceback (most recent call last):
  File "/home/screen/.local/pipx/venvs/lnxlink/lib/python3.11/site-packages/lnxlink/__main__.py", line 196, in setup_mqtt
    self.client.connect(
  File "/home/screen/.local/pipx/venvs/lnxlink/lib/python3.11/site-packages/paho/mqtt/client.py", line 1429, in connect
    return self.reconnect()
           ^^^^^^^^^^^^^^^^
  File "/home/screen/.local/pipx/venvs/lnxlink/lib/python3.11/site-packages/paho/mqtt/client.py", line 1592, in reconnect
    self._sock = self._create_socket()
                 ^^^^^^^^^^^^^^^^^^^^^
  File "/home/screen/.local/pipx/venvs/lnxlink/lib/python3.11/site-packages/paho/mqtt/client.py", line 4598, in _create_socket
    sock = self._create_socket_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/screen/.local/pipx/venvs/lnxlink/lib/python3.11/site-packages/paho/mqtt/client.py", line 4623, in _create_socket_connection
    return socket.create_connection(addr, timeout=self._connect_timeout, source_address=source)

**Comment by bkbilly** [comment]
It seems that it can't connect to the MQTT broker. Make sure it accepts connections from your machine.
Also make sure you have setup correctly your `/opt/lnxlink/config.yaml` file.
A nice app to try is the [MQTT Explorer](https://mqtt-explorer.com/).

**Comment by emarvegt** [comment]
Turns out I had a typo in the ip address pointing to my mqtt broker due to a faulty keyboard... oops...
It's working now. Thanks for the help! Closing this issue now.
