### ISSUE TITLE
[feature request] Update instructions

### ISSUE THREAD

**Issue by Dinth** [bkbilly/lnxlink#95]
### Describe the solution you'd like

Hi. I know this is something really straightforward, but when i was starting with lnxlink a while ago i had issues caused by not following the official installation instruction, so i think that we also should have an official update instruction just to be confident that nothing will be broken in the process.

**Comment by bkbilly** [comment]
I have been working on how to make the installation as easy as possible, but every distribution has it's own dependencies, so it's hard finding what needs to be installed.
I've created a script that makes it easy to install it which can also work as an update script. As far as I am aware, it works on most Linux distributions:
```bash
curl -L https://raw.githubusercontent.com/bkbilly/lnxlink/master/install.sh | bash
```

My recommended and faster way to update is to use the update module on your configuration which is enabled by default.
This checks for the latest release every 24 hours and if a new version is found, an install option is shown on Home Assistant.
If you don't use Home Assistant, or want to do this manually, you can start the update process with an MQTT message as described [here](https://bkbilly.gitbook.io/lnxlink/examples#install-update).

**Comment by Dinth** [comment]
When was the update module introduced? Im running 2023.10.0 and publishing the message doesnt work

**Comment by bkbilly** [comment]
It was first used on version `2023.12.0` that worked if it was installed with pip on the system.
It became more generic, including PIPX and manual virtual environment, on the version `2024.2.1`.

**Comment by bkbilly** [comment]
The latest versions of LNXlink can auto update, so I consider this issue fixed and I'll close it.
If you still have issues updating, feel free to reopen it.
